This notebook takes in as input the raw files for cell lines obtained from the CCLE website (build 21Q3) - https://depmap.org/portal/download/all/

* mutations - CCLE_mutations.csv
* gene expression - CCLE_expression.csv
* audrc scores - sanger_dose_response.csv (search for this file in the search bar of the above link)

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_dir = "../../datasets/NCMF/CellLine/"

In [3]:
gene_exp = pd.read_csv(data_dir + "CCLE_expression.csv", index_col = 0)
print(gene_exp.shape)
gene_exp

(1377, 19177)

,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),C1orf112 (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),NFYA (4800),...,ARHGAP11B (89839),AC004593.2 (1124),AC090517.4 (54816),AL160269.1 (11046),ABCF2-H2BE1 (114483834),POLR2J3 (548644),H2BE1 (114483833),AL445238.1 (647264),GET1-SH3BGR (106865373),AC113348.1 (102724657)
ACH-001113,4.990501,0.000000,7.273702,2.765535,4.480265,0.028569,1.269033,3.058316,6.483171,5.053980,...,1.214125,0.000000,0.111031,0.150560,1.427606,5.781884,0.000000,0.000000,0.799087,0.000000
ACH-001289,5.209843,0.545968,7.070604,2.538538,3.510962,0.000000,0.176323,3.836934,4.200850,3.832890,...,1.835924,0.000000,0.310340,0.000000,0.807355,4.704319,0.000000,0.000000,0.464668,0.070389
ACH-001339,3.779260,0.000000,7.346425,2.339137,4.254745,0.056584,1.339137,6.724241,3.671293,3.775051,...,1.823749,0.084064,0.176323,0.042644,1.384050,4.931683,0.000000,0.028569,0.263034,0.000000
ACH-001538,5.726831,0.000000,7.086189,2.543496,3.102658,0.000000,5.914565,6.099716,4.475733,4.294253,...,0.871844,0.137504,0.263034,2.485427,0.713696,3.858976,0.000000,0.000000,0.000000,0.000000
ACH-000242,7.465648,0.000000,6.435462,2.414136,3.864929,0.831877,7.198003,5.452530,7.112492,4.710944,...,2.324811,0.163499,0.163499,0.000000,1.117695,4.990501,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000750,4.173127,0.000000,6.400879,1.807355,3.303050,0.014355,0.137504,4.944858,4.528571,4.383359,...,1.280956,0.176323,0.084064,0.000000,2.615887,5.102658,0.000000,0.097611,0.214125,0.000000
ACH-000285,0.097611,0.000000,6.428276,3.257011,4.980482,0.411426,0.124328,0.704872,4.829342,5.393348,...,2.939227,0.000000,0.014355,0.000000,3.326250,6.341630,0.000000,0.000000,0.310340,0.000000
ACH-001858,5.045268,0.000000,6.991749,1.807355,3.270529,0.028569,3.333424,6.819796,5.395063,3.727920,...,1.510962,0.056584,0.097611,0.286881,1.925999,4.607626,0.111031,0.000000,1.090853,0.000000
ACH-001997,5.805292,0.000000,7.792855,2.482848,3.903038,0.028569,4.124328,6.816600,4.458119,3.664483,...,0.757023,0.150560,0.432959,0.111031,0.613532,4.787119,0.000000,0.163499,0.084064,0.000000
ACH-000052,4.870858,0.000000,6.077457,2.304511,3.836934,0.201634,1.339137,3.491853,3.940167,4.621759,...,2.648465,0.903038,0.356144,0.000000,2.778209,4.452859,0.000000,0.163499,1.422233,0.000000

In [4]:
mut = pd.read_csv(data_dir + "CCLE_mutations.csv")
mut

/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (3,19,22,27,28,29,30,31) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Hugo_Symbol,Entrez_Gene_Id,NCBI_Build,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,...,isCOSMIChotspot,COSMIChsCnt,ExAC_AF,Variant_annotation,CGA_WES_AC,HC_AC,RD_AC,RNAseq_AC,SangerWES_AC,WGS_AC
0,VPS13D,55187,37,1,12359347,12359347,+,Nonsense_Mutation,SNP,C,...,False,0.0,NaN,damaging,34:213,NaN,NaN,NaN,34:221,NaN
1,AADACL4,343066,37,1,12726308,12726322,+,In_Frame_Del,DEL,CTGGCGTGACGCCAT,...,False,3.0,NaN,other non-conserving,57:141,NaN,NaN,NaN,9:0,28:32
2,IFNLR1,163702,37,1,24484172,24484172,+,Silent,SNP,G,...,False,0.0,NaN,silent,118:0,NaN,NaN,10:0,118:0,18:0
3,TMEM57,55219,37,1,25785018,25785019,+,Frame_Shift_Ins,INS,-,...,False,0.0,NaN,damaging,NaN,NaN,NaN,6:28,NaN,NaN
4,ZSCAN20,7579,37,1,33954141,33954141,+,Missense_Mutation,SNP,T,...,False,0.0,NaN,other non-conserving,28:62,NaN,NaN,NaN,27:61,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226331,SLC39A4,55630,37,8,145641991,145641991,+,Silent,SNP,C,...,False,0.0,0.000017,silent,52:23,NaN,NaN,NaN,NaN,NaN
1226332,TAL2,6887,37,9,108424778,108424778,+,Start_Codon_SNP,SNP,A,...,False,0.0,NaN,damaging,27:0,NaN,NaN,NaN,NaN,NaN
1226333,TRO,7216,37,X,54955098,54955098,+,Silent,SNP,C,...,False,0.0,NaN,silent,5:16,NaN,NaN,NaN,NaN,NaN
1226334,USP51,158880,37,X,55514703,55514703,+,Missense_Mutation,SNP,G,...,False,0.0,NaN,other non-conserving,23:0,NaN,NaN,NaN,NaN,NaN
1226335,C1GALT1C1,29071,37,X,119760406,119760406,+,Missense_Mutation,SNP,T,...,False,0.0,NaN,other non-conserving,28:0,NaN,NaN,NaN,NaN,NaN

In [5]:
mut.Variant_Type.value_counts()

SNP    1142836
DEL      52952
INS      29924
DNP        622
TNP          2
Name: Variant_Type, dtype: int64

In [6]:
mut.Variant_Classification.value_counts()

Missense_Mutation           703276
Silent                      354408
Splice_Site                  42743
Frame_Shift_Del              41864
Nonsense_Mutation            40522
Frame_Shift_Ins              24802
In_Frame_Del                  7738
De_novo_Start_OutOfFrame      4341
In_Frame_Ins                  3183
Start_Codon_SNP               1372
Nonstop_Mutation               958
Intron                         342
Stop_Codon_Del                 178
Start_Codon_Del                141
Stop_Codon_Ins                 130
Start_Codon_Ins                 92
IGR                             85
5'Flank                         73
3'UTR                           56
5'UTR                           32
Name: Variant_Classification, dtype: int64

In [7]:
mut.Variant_annotation.value_counts()

other non-conserving    715463
silent                  354408
damaging                155877
other conserving           588
Name: Variant_annotation, dtype: int64

In [8]:
cnv = pd.read_csv(data_dir + "CCLE_cn_segments_annotated_21Q3.txt", sep = "\t")
cnv

,chr,segment_start,segment_end,status,DepMap-ID,gene_chr,gene_start,gene_end,ensembl_id,genesymbol
0,chr1,0,6275858,+,ACH-000001,chr1,450702,451697,ENSG00000284733.1,OR4F29
1,chr1,0,6275858,+,ACH-000001,chr1,685678,686673,ENSG00000284662.1,OR4F16
2,chr1,0,6275858,+,ACH-000001,chr1,960586,965715,ENSG00000187961.13,KLHL17
3,chr1,0,6275858,+,ACH-000001,chr1,975203,982093,ENSG00000187642.9,PERM1
4,chr1,0,6275858,+,ACH-000001,chr1,1001137,1014540,ENSG00000187608.9,ISG15
...,...,...,...,...,...,...,...,...,...,...
35049414,chrY,22359501,26397001,-,ACH-002512,chrY,24833842,24907040,ENSG00000205916.11,DAZ4
35049415,chrY,22359501,26397001,-,ACH-002512,chrY,25030900,25062548,ENSG00000185894.8,BPY2C
35049416,chrY,56750001,57227415,+,ACH-002512,chrY,56954331,56968979,ENSG00000168939.11_PAR_Y,SPRY3
35049417,chrY,56750001,57227415,+,ACH-002512,chrY,57067812,57130289,ENSG00000124333.15_PAR_Y,VAMP7
35049418,chrY,56750001,57227415,+,ACH-002512,chrY,57184100,57197337,ENSG00000124334.17_PAR_Y,IL9R

In [9]:
audrc = pd.read_csv(data_dir + "sanger-dose-response.csv")
audrc

,DATASET,COSMIC_ID,DRUG_ID,MIN_CONC,MAX_CONC,RMSE_PUBLISHED,Z_SCORE_PUBLISHED,IC50_PUBLISHED,AUC_PUBLISHED,ARXSPAN_ID,DRUG_NAME,BROAD_ID,upper_limit,ec50,slope,lower_limit,auc,log2.ic50,mse,R2
0,GDSC1,683665,1,0.007813,2.0,0.022518,-0.192056,10.977393,0.982116,ACH-002270,ERLOTINIB,BRD-K70401845,0.992788,2.839376e+00,-5.670993,0.514389,0.990834,NaN,0.000034,0.904675
1,GDSC1,684055,1,0.007813,2.0,0.031831,0.505823,23.133991,0.984820,ACH-002104,ERLOTINIB,BRD-K70401845,1.006405,2.864875e-02,-0.186377,0.990054,0.997138,NaN,0.000057,0.028903
2,GDSC1,684057,1,0.007813,2.0,0.026047,1.280750,52.935278,0.985696,ACH-002106,ERLOTINIB,BRD-K70401845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GDSC1,684059,1,0.007813,2.0,0.110056,0.086028,14.774223,0.972701,ACH-002108,ERLOTINIB,BRD-K70401845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GDSC1,684062,1,0.007813,2.0,0.087010,-0.114395,11.926884,0.944463,ACH-002111,ERLOTINIB,BRD-K70401845,0.989580,7.580375e-02,-12.222777,0.894027,0.933185,NaN,0.000623,0.777093
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387621,GDSC2,905951,2172,0.009766,10.0,0.143863,0.042524,25.410793,0.877741,ACH-000288,JQ1,"BRD-K54606188, NA",3.929045,3.287745e+11,-0.012190,-3.449953,0.856099,NaN,0.006178,0.292447
387622,GDSC2,906862,2172,0.009766,10.0,0.088631,-2.223819,0.339325,0.510590,ACH-001065,JQ1,"BRD-K54606188, NA",0.935866,4.096968e-01,-2.014115,0.176515,0.585800,-1.073816,0.003198,0.971991
387623,GDSC2,907046,2172,0.009766,10.0,0.114748,-0.578942,7.780877,0.843211,ACH-000930,JQ1,"BRD-K54606188, NA",0.960799,3.695946e-01,-1.161533,0.687792,0.830671,NaN,0.002792,0.795935
387624,GDSC2,749709,2172,0.009766,10.0,0.047625,1.642265,534.688321,0.983634,ACH-000859,JQ1,"BRD-K54606188, NA",0.977260,1.161541e+30,-0.031889,0.900234,0.969870,NaN,0.000879,0.000540
387625,GDSC2,906801,2172,0.009766,10.0,0.085767,0.858430,120.177282,0.952633,ACH-000536,JQ1,"BRD-K54606188, NA",0.961719,7.840383e+01,-0.554315,0.664756,0.940827,NaN,0.003325,0.159037

In [10]:
overlapping_ids = set(gene_exp.index) & set(mut.DepMap_ID) & set(cnv["DepMap-ID"]) & set(audrc.ARXSPAN_ID)
len(overlapping_ids)

692

#### Mutation processing

In [11]:
mut_reduced = mut[mut.DepMap_ID.isin(overlapping_ids)]

In [12]:
mutation_filtered = mut_reduced[['Hugo_Symbol', 'Variant_annotation','DepMap_ID']]

mutations_needed = ['damaging', 'other non-conserving']
mutation_filtered = mutation_filtered[mutation_filtered['Variant_annotation'].isin(mutations_needed)]

# binary file
mutation_filtered['mutated'] = 1
mutation_filtered_1 = pd.pivot_table(mutation_filtered, 'mutated', index=['DepMap_ID'], columns=['Hugo_Symbol'], aggfunc = 'first')
mutation_filtered_1.fillna(0,inplace=True)

In [13]:
mutation_filtered_1

Hugo_Symbol,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3,hsa-mir-1199
DepMap_ID,,,,,,,,,,,,,,,,,,,,,
ACH-000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001715,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001716,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

#### CNV processing

In [14]:
cnv_reduced = cnv[cnv["DepMap-ID"].isin(overlapping_ids)]

In [15]:
cnv_filtered = pd.pivot_table(cnv_reduced, 'status', index=['DepMap-ID'], columns=['genesymbol'], aggfunc = 'first')

In [16]:
cnv_filtered1 = cnv_filtered.replace({'U':0, '+':1, '-':-1})

In [17]:
cnv_filtered1

genesymbol,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
DepMap-ID,,,,,,,,,,,,,,,,,,,,,
ACH-000001,-1,1,0,0,0,-1,1,1,0,1,...,-1,0,1,0,0,1,1,0,0,-1
ACH-000002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
ACH-000004,1,-1,1,1,1,-1,1,1,1,1,...,1,1,-1,0,0,1,1,1,-1,-1
ACH-000006,0,0,-1,-1,0,-1,0,-1,-1,0,...,0,1,0,0,0,0,0,0,0,-1
ACH-000007,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,1,0,0,0,-1,-1,0,0,0,0,...,-1,-1,0,0,0,0,-1,-1,1,1
ACH-001703,0,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-001711,0,-1,0,0,-1,-1,-1,0,0,-1,...,1,0,-1,0,0,-1,-1,-1,0,1
ACH-001715,-1,-1,1,1,-1,1,0,0,0,0,...,0,1,0,0,0,0,1,1,-1,-1
ACH-001716,0,0,0,0,-1,0,0,0,0,0,...,-1,0,0,0,0,0,0,0,1,0

#### Gene expression processing

In [18]:
gene_exp_reduced = gene_exp[gene_exp.index.isin(overlapping_ids)]
gene_expression_1 = gene_exp_reduced.rename(columns=lambda x: x.split('(')[0].strip())

In [19]:
gene_expression_1

,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,NFYA,...,ARHGAP11B,AC004593.2,AC090517.4,AL160269.1,ABCF2-H2BE1,POLR2J3,H2BE1,AL445238.1,GET1-SH3BGR,AC113348.1
ACH-000242,7.465648,0.000000,6.435462,2.414136,3.864929,0.831877,7.198003,5.452530,7.112492,4.710944,...,2.324811,0.163499,0.163499,0.000000,1.117695,4.990501,0.000000,0.000000,0.000000,0.000000
ACH-000327,4.032982,0.000000,5.806582,1.948601,2.684819,0.014355,3.117695,5.977509,3.653060,3.014355,...,0.799087,0.669027,0.070389,0.000000,1.090853,4.996841,0.000000,0.042644,0.286881,0.028569
ACH-000233,0.097611,0.000000,5.919102,3.983678,3.733354,0.028569,6.111240,2.963474,3.415488,4.820690,...,1.883621,0.000000,0.056584,0.014355,3.356144,6.839960,0.000000,0.000000,2.280956,0.000000
ACH-000528,5.236493,0.000000,7.005849,2.829850,4.666757,0.014355,0.823749,6.607478,3.975447,4.362470,...,1.700440,0.137504,0.070389,0.000000,1.847997,4.635174,0.000000,0.000000,0.367371,0.000000
ACH-001655,4.376429,0.000000,6.679480,0.925999,1.867896,0.042644,0.056584,5.394034,1.839960,2.634593,...,0.632268,0.000000,0.014355,0.000000,0.163499,3.829850,0.137504,0.000000,1.214125,0.084064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-000830,3.956057,0.000000,6.337533,2.531069,4.683135,0.310340,0.084064,0.925999,3.795975,5.661351,...,2.157044,0.310340,0.275007,0.028569,2.053111,5.379552,0.000000,0.000000,0.855990,0.000000
ACH-000114,3.793896,0.028569,6.330738,2.792855,2.643856,0.565597,4.783980,5.748193,5.551208,4.272023,...,1.356144,0.400538,0.042644,0.807355,2.220330,3.793896,0.000000,0.000000,1.416840,0.084064
ACH-000973,5.026800,0.000000,6.966130,1.899176,3.531069,0.000000,3.910733,6.371385,4.693208,5.029453,...,1.952334,0.042644,0.042644,0.042644,3.104337,5.934281,0.000000,0.000000,0.378512,0.000000
ACH-000750,4.173127,0.000000,6.400879,1.807355,3.303050,0.014355,0.137504,4.944858,4.528571,4.383359,...,1.280956,0.176323,0.084064,0.000000,2.615887,5.102658,0.000000,0.097611,0.214125,0.000000
ACH-000052,4.870858,0.000000,6.077457,2.304511,3.836934,0.201634,1.339137,3.491853,3.940167,4.621759,...,2.648465,0.903038,0.356144,0.000000,2.778209,4.452859,0.000000,0.163499,1.422233,0.000000

In [20]:
overlapping_genes = list(set(mutation_filtered_1.columns) & set(cnv_filtered1.columns) & set(gene_expression_1.columns))
overlapping_genes = sorted(overlapping_genes)
len(overlapping_genes)

17515

In [21]:
mut_csv = mutation_filtered_1[overlapping_genes]
mut_csv = mut_csv.sort_index()
mut_csv

Hugo_Symbol,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
DepMap_ID,,,,,,,,,,,,,,,,,,,,,
ACH-000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-000007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001703,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001711,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001715,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACH-001716,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [22]:
cnv_csv = cnv_filtered1[overlapping_genes]
cnv_csv = cnv_csv.sort_index()
cnv_csv

genesymbol,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
DepMap-ID,,,,,,,,,,,,,,,,,,,,,
ACH-000001,-1,1,0,0,0,-1,1,1,0,1,...,-1,0,1,0,0,1,1,0,0,-1
ACH-000002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1
ACH-000004,1,-1,1,1,1,-1,1,1,1,1,...,1,1,-1,0,0,1,1,1,-1,-1
ACH-000006,0,0,-1,-1,0,-1,0,-1,-1,0,...,0,1,0,0,0,0,0,0,0,-1
ACH-000007,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,1,0,0,0,-1,-1,0,0,0,0,...,-1,-1,0,0,0,0,-1,-1,1,1
ACH-001703,0,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-001711,0,-1,0,0,-1,-1,-1,0,0,-1,...,1,0,-1,0,0,-1,-1,-1,0,1
ACH-001715,-1,-1,1,1,-1,1,0,0,0,0,...,0,1,0,0,0,0,1,1,-1,-1
ACH-001716,0,0,0,0,-1,0,0,0,0,0,...,-1,0,0,0,0,0,0,0,1,0

In [23]:
gene_exp_csv = gene_expression_1[overlapping_genes]
gene_exp_csv = gene_exp_csv.sort_index()
gene_exp_csv

,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
ACH-000001,3.122673,0.056584,0.250962,0.111031,0.000000,1.035624,0.176323,5.845741,4.125155,0.815575,...,3.415488,5.049631,6.695715,0.948601,1.839960,4.696550,3.273516,2.811471,6.825786,3.005400
ACH-000002,1.416840,0.000000,0.286881,0.111031,0.000000,0.150560,0.000000,5.221877,1.967169,0.000000,...,2.765535,3.176323,6.398487,0.056584,0.963474,3.951401,0.000000,1.090853,6.019924,2.195348
ACH-000004,4.180307,0.000000,0.286881,0.344828,0.070389,0.097611,0.000000,6.430620,3.212569,0.000000,...,3.838952,4.242603,6.119356,0.765535,1.545968,3.617063,0.014355,2.070389,7.036503,3.436961
ACH-000006,3.945795,0.014355,0.000000,0.070389,0.000000,0.042644,0.070389,5.667608,3.218781,0.000000,...,3.949535,4.143230,7.929318,1.137504,1.835924,4.955127,0.056584,2.107688,5.816856,3.693766
ACH-000007,0.137504,1.510962,0.214125,0.000000,0.000000,0.014355,0.000000,5.582857,4.274262,3.549669,...,3.670161,3.760221,6.179312,0.565597,1.682573,3.862947,0.014355,1.992768,6.365448,3.658783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,4.162693,0.000000,0.000000,0.000000,0.000000,3.802193,0.000000,5.754353,3.196922,0.000000,...,3.028569,4.084064,6.422065,0.978196,1.989139,1.811471,1.321928,2.039138,6.993561,3.106013
ACH-001703,4.884109,0.000000,0.014355,0.000000,0.056584,4.474436,0.000000,6.053329,5.379898,0.000000,...,2.163499,2.454176,4.032101,0.422233,0.970854,3.273516,0.000000,0.773996,2.646163,2.545968
ACH-001711,5.245648,0.000000,0.422233,0.000000,0.000000,1.669027,0.000000,5.270529,3.418190,0.443607,...,3.996389,4.555203,6.205353,0.124328,1.250962,2.451541,0.367371,2.361768,5.532317,2.792855
ACH-001715,4.357552,0.042644,0.321928,0.000000,0.000000,0.613532,0.000000,4.564988,3.396434,0.000000,...,4.469235,5.151778,6.671293,0.432959,1.691534,2.664483,1.454176,3.209453,6.297925,2.503349
ACH-001716,2.375735,0.014355,0.000000,0.000000,0.000000,0.641546,0.000000,6.206526,4.310340,0.000000,...,3.495695,4.806324,6.913966,0.000000,1.536053,2.871844,0.344828,2.682573,6.446752,2.931683

In [24]:
print("Mean", np.mean(gene_exp_csv.values))
print("Min", np.min(gene_exp_csv.values))
print("Max", np.max(gene_exp_csv.values))
print("Median", np.median(gene_exp_csv.values))

Mean 2.723538999463561
Min 0.0
Max 15.757676477988904
Median 2.563158130402808

In [25]:
# scaling gene expression
from sklearn.preprocessing import StandardScaler
gene_exp_scaler = StandardScaler()
gene_exp_scaled = gene_exp_scaler.fit_transform(gene_exp_csv.values)
print("Mean", np.mean(gene_exp_scaled))
print("Min", np.min(gene_exp_scaled))
print("Max", np.max(gene_exp_scaled))
print("Median", np.median(gene_exp_scaled))

Mean 6.680768273537712e-18
Min -12.925144633629657
Max 26.286878856189837
Median -0.15936935061592533

In [26]:
gene_exp_scaled_csv = pd.DataFrame(gene_exp_scaled)
gene_exp_scaled_csv.columns = list(gene_exp_csv.columns)
gene_exp_scaled_csv.index = list(gene_exp_csv.index)
gene_exp_scaled_csv

,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,AADAC,...,ZW10,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1
ACH-000001,0.036144,-0.248412,-0.295127,-0.254399,-0.353017,-0.693902,0.385289,0.332306,-0.102226,0.199578,...,-0.653130,0.974872,0.210452,-0.209604,-0.334714,1.516574,1.958621,0.322393,0.577335,-0.780504
ACH-000002,-0.793958,-0.316441,-0.272834,-0.254399,-0.353017,-1.228306,-0.369392,-0.831150,-2.879069,-0.494509,...,-1.709988,-1.785626,-0.145588,-1.620057,-1.755439,0.379276,-0.973068,-2.433694,0.064766,-1.945488
ACH-000004,0.550817,-0.316441,-0.272834,0.008722,0.642809,-1.260277,-0.369392,1.423058,-1.276518,-0.494509,...,0.035443,-0.214361,-0.479950,-0.499067,-0.811254,-0.131014,-0.960211,-0.864672,0.711363,-0.159850
ACH-000006,0.436697,-0.299182,-0.450882,-0.300138,-0.353017,-1.293465,-0.068118,0.000103,-1.268525,-0.494509,...,0.215257,-0.360796,1.688142,0.089089,-0.341255,1.911231,-0.922393,-0.804928,-0.064396,0.209475
ACH-000007,-1.416517,1.500143,-0.317989,-0.379356,-0.353017,-1.310546,-0.369392,-0.157952,0.089641,2.526402,...,-0.239020,-0.925197,-0.408131,-0.815207,-0.589827,0.244271,-0.960211,-0.989006,0.284537,0.159164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,0.542246,-0.316441,-0.450882,-0.379356,-0.353017,0.976560,-0.369392,0.161875,-1.296653,-0.494509,...,-1.282281,-0.447982,-0.117346,-0.162808,-0.092904,-2.886834,0.210822,-0.914730,0.684049,-0.635806
ACH-001703,0.893305,-0.316441,-0.441973,-0.379356,0.447493,1.382461,-0.369392,0.719440,1.512347,-0.494509,...,-2.688930,-2.849779,-2.980204,-1.041894,-1.743477,-0.655360,-0.973068,-2.941236,-2.081119,-1.441239
ACH-001711,1.069239,-0.316441,-0.188831,-0.379356,-0.353017,-0.311452,-0.369392,-0.740418,-1.011931,-0.116982,...,0.291444,0.246285,-0.376937,-1.512940,-1.289441,-1.909915,-0.644058,-0.397941,-0.245377,-1.086177
ACH-001715,0.637069,-0.265171,-0.251083,-0.379356,-0.353017,-0.948762,-0.369392,-2.056196,-1.039926,-0.494509,...,1.060316,1.125395,0.181197,-1.024934,-0.575302,-1.584908,0.329260,0.959881,0.241589,-1.502533
ACH-001716,-0.327335,-0.299182,-0.450882,-0.379356,-0.353017,-0.931847,-0.369392,1.005141,0.136066,-0.494509,...,-0.522710,0.616337,0.471887,-1.709527,-0.827326,-1.268420,-0.664247,0.115924,0.336251,-0.886520

#### AUDRC Processing

In [27]:
audrc_reduced = audrc[audrc["ARXSPAN_ID"].isin(overlapping_ids)]

In [28]:
audrc_reduced['DRUG_NAME_new'] = audrc_reduced['DRUG_NAME'].str.split(',').str[0]

/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [29]:
#take the latest drug auc value
cellline_drug_auc = pd.pivot_table(audrc_reduced, 'AUC_PUBLISHED', index=['ARXSPAN_ID'], columns=['DRUG_NAME_new'], aggfunc = 'last')

In [30]:
cellline_drug_auc

DRUG_NAME_new,(5Z)-7-OXOZEAENOL,5-FLUOROURACIL,681640,A-443654,A-770041,A-83-01,ABT-737,ACETALAX,ACY-1215,AFATINIB,...,Y-39983,YK-4-279,YM-155,YM-201636,Z-LLNLE-CHO,ZG-10,ZIBOTENTAN,ZM-447439,ZOLEDRONATE,ZSTK-474
ARXSPAN_ID,,,,,,,,,,,,,,,,,,,,,
ACH-000001,0.778432,0.951321,0.840287,NaN,NaN,0.936410,0.891908,0.402122,0.659600,0.835903,...,0.982272,0.733492,0.072277,0.983536,NaN,0.651746,0.982084,0.893777,0.983861,0.933035
ACH-000002,0.788327,0.874760,0.760137,0.905754,0.930764,0.991068,0.278288,0.972905,0.558774,0.890106,...,0.899628,0.604228,0.046061,0.918265,0.865628,NaN,0.985921,0.839175,0.988639,0.533204
ACH-000004,0.737630,0.938733,0.835441,0.808964,0.966133,0.983552,NaN,0.993912,0.596027,0.960320,...,0.965245,0.782295,0.366912,0.844979,0.761323,NaN,0.980945,0.946694,0.992605,0.761956
ACH-000006,0.176396,0.571569,0.581729,0.585938,0.958510,0.935574,0.600428,NaN,0.596056,0.690723,...,0.834158,0.605360,0.124930,0.813384,0.782187,NaN,0.971058,0.871277,NaN,0.495020
ACH-000007,0.569751,0.755449,0.954924,0.939587,0.965638,0.932666,NaN,0.956481,0.838692,0.704093,...,0.927519,0.812955,0.719780,0.815099,0.795736,0.860768,0.983317,0.888067,0.987564,0.787948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,0.666638,0.896186,0.891133,0.624125,0.922527,NaN,0.969217,0.963402,0.937571,0.913293,...,0.979778,0.836984,0.072806,0.956333,0.726613,0.721385,0.984953,0.847681,0.979249,0.958591
ACH-001703,0.622453,0.814459,0.637895,NaN,NaN,0.864438,0.392579,0.977295,0.659719,0.801995,...,0.784185,0.593771,0.060970,0.800455,NaN,0.767454,0.982716,0.876474,0.990392,0.497201
ACH-001711,NaN,0.976946,0.827778,NaN,NaN,0.964134,0.654764,0.968055,0.617542,0.849041,...,0.897094,0.783757,0.131479,0.956406,NaN,0.553855,0.985985,0.924509,0.932340,0.815928
ACH-001715,0.603062,0.915064,0.710602,NaN,NaN,0.976210,0.902000,0.943489,0.831464,0.822851,...,0.978098,0.820708,0.115805,0.978112,NaN,NaN,0.975895,0.881961,0.968001,0.981441
ACH-001716,0.701090,0.819045,0.725729,0.724840,0.880880,0.974594,0.917531,0.957557,0.522027,0.876267,...,0.917595,0.730460,0.254550,0.830955,0.956865,NaN,0.975168,0.871995,0.975417,0.942321

In [31]:
np.where(cellline_drug_auc.values == 1)

(array([], dtype=int64), array([], dtype=int64))

##### Imputing NaN values with KNN

In [32]:
from sklearn.impute import KNNImputer

In [33]:
# combining mutations, cnv, unscaled gene exp (17515 genes), raw audrc
knn_input_matrix = np.concatenate((mut_csv.values, cnv_csv.values, gene_exp_csv.values, cellline_drug_auc.values), axis = 1)
knn_input_matrix.shape

(692, 52941)

In [34]:
imputer = KNNImputer(n_neighbors=5)
imputer.fit(knn_input_matrix) # fit on combined matrix of mutations, cnv, unscaled gene exp and raw audrc

KNNImputer()

In [35]:
imputed_np = imputer.transform(knn_input_matrix)
imputed_np.shape

(692, 52941)

In [36]:
imputed_np[:, -396:].shape

(692, 396)

In [37]:
cellline_drug_auc_imputed = pd.DataFrame(imputed_np[:, -396:])
cellline_drug_auc_imputed.columns = list(cellline_drug_auc.columns)
cellline_drug_auc_imputed.index = list(cellline_drug_auc.index)
cellline_drug_auc_imputed

,(5Z)-7-OXOZEAENOL,5-FLUOROURACIL,681640,A-443654,A-770041,A-83-01,ABT-737,ACETALAX,ACY-1215,AFATINIB,...,Y-39983,YK-4-279,YM-155,YM-201636,Z-LLNLE-CHO,ZG-10,ZIBOTENTAN,ZM-447439,ZOLEDRONATE,ZSTK-474
ACH-000001,0.778432,0.951321,0.840287,0.648689,0.788562,0.936410,0.891908,0.402122,0.659600,0.835903,...,0.982272,0.733492,0.072277,0.983536,0.856555,0.651746,0.982084,0.893777,0.983861,0.933035
ACH-000002,0.788327,0.874760,0.760137,0.905754,0.930764,0.991068,0.278288,0.972905,0.558774,0.890106,...,0.899628,0.604228,0.046061,0.918265,0.865628,0.554357,0.985921,0.839175,0.988639,0.533204
ACH-000004,0.737630,0.938733,0.835441,0.808964,0.966133,0.983552,0.627463,0.993912,0.596027,0.960320,...,0.965245,0.782295,0.366912,0.844979,0.761323,0.605560,0.980945,0.946694,0.992605,0.761956
ACH-000006,0.176396,0.571569,0.581729,0.585938,0.958510,0.935574,0.600428,0.971874,0.596056,0.690723,...,0.834158,0.605360,0.124930,0.813384,0.782187,0.556358,0.971058,0.871277,0.986794,0.495020
ACH-000007,0.569751,0.755449,0.954924,0.939587,0.965638,0.932666,0.849279,0.956481,0.838692,0.704093,...,0.927519,0.812955,0.719780,0.815099,0.795736,0.860768,0.983317,0.888067,0.987564,0.787948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,0.666638,0.896186,0.891133,0.624125,0.922527,0.955971,0.969217,0.963402,0.937571,0.913293,...,0.979778,0.836984,0.072806,0.956333,0.726613,0.721385,0.984953,0.847681,0.979249,0.958591
ACH-001703,0.622453,0.814459,0.637895,0.652835,0.462459,0.864438,0.392579,0.977295,0.659719,0.801995,...,0.784185,0.593771,0.060970,0.800455,0.792641,0.767454,0.982716,0.876474,0.990392,0.497201
ACH-001711,0.691805,0.976946,0.827778,0.712041,0.834897,0.964134,0.654764,0.968055,0.617542,0.849041,...,0.897094,0.783757,0.131479,0.956406,0.913714,0.553855,0.985985,0.924509,0.932340,0.815928
ACH-001715,0.603062,0.915064,0.710602,0.783734,0.774396,0.976210,0.902000,0.943489,0.831464,0.822851,...,0.978098,0.820708,0.115805,0.978112,0.826959,0.783528,0.975895,0.881961,0.968001,0.981441
ACH-001716,0.701090,0.819045,0.725729,0.724840,0.880880,0.974594,0.917531,0.957557,0.522027,0.876267,...,0.917595,0.730460,0.254550,0.830955,0.956865,0.803726,0.975168,0.871995,0.975417,0.942321

In [38]:
print("Mean", np.mean(cellline_drug_auc_imputed.values))
print("Min", np.min(cellline_drug_auc_imputed.values))
print("Max", np.max(cellline_drug_auc_imputed.values))
print("Median", np.median(cellline_drug_auc_imputed.values))

Mean 0.8516737786565072
Min 0.004496
Max 0.999883
Median 0.9248416

In [39]:
audrc_csv = cellline_drug_auc

In [40]:
audrc_csv_binary = pd.DataFrame(cellline_drug_auc_imputed.values < 0.25)
audrc_csv_binary = audrc_csv_binary.astype(int)
audrc_csv_binary.index = list(cellline_drug_auc.index)
audrc_csv_binary.columns = list(cellline_drug_auc.columns)
audrc_csv_binary

/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.

,(5Z)-7-OXOZEAENOL,5-FLUOROURACIL,681640,A-443654,A-770041,A-83-01,ABT-737,ACETALAX,ACY-1215,AFATINIB,...,Y-39983,YK-4-279,YM-155,YM-201636,Z-LLNLE-CHO,ZG-10,ZIBOTENTAN,ZM-447439,ZOLEDRONATE,ZSTK-474
ACH-000001,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
ACH-000002,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
ACH-000004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ACH-000006,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
ACH-000007,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACH-001702,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
ACH-001703,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
ACH-001711,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
ACH-001715,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
ACH-001716,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [41]:
audrc_cell_count = audrc_csv_binary.shape[0] * audrc_csv_binary.shape[1]
print(audrc_cell_count)

274032

In [42]:
print(f"Percentage of ones in AUDRC data = {np.count_nonzero(audrc_csv_binary.values)/audrc_cell_count}")
print(f"Percentage of zeros in AUDRC data = {1-(np.count_nonzero(audrc_csv_binary.values)/audrc_cell_count)}")

Percentage of ones in AUDRC data = 0.013991066736731476
Percentage of zeros in AUDRC data = 0.9860089332632685

#### Create csv files for NCMF consumption

In [43]:
oncokb_genes = pd.read_csv("../../datasets/NCMF/CellLine/cancerGeneList.tsv", sep="\t") # ref https://www.oncokb.org/cancerGenes
oncokb_genes

,Hugo Symbol,Entrez Gene ID,GRCh37 Isoform,GRCh37 RefSeq,GRCh38 Isoform,GRCh38 RefSeq,# of occurrence within resources (Column D-J),OncoKB Annotated,Is Oncogene,Is Tumor Suppressor Gene,MSK-IMPACT,MSK-HEME,FOUNDATION ONE,FOUNDATION ONE HEME,Vogelstein,SANGER CGC(05/30/2017),Gene Aliases
0,ABL1,25,ENST00000318560,NM_005157.4,ENST00000318560,NM_005157.4,7,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,"ABL, JTK7, c-ABL"
1,AKT1,207,ENST00000349310,NM_001014431.1,ENST00000349310,NM_001014431.1,7,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,"AKT, PKB, PRKBA, RAC, RAC-alpha"
2,ALK,238,ENST00000389048,NM_004304.4,ENST00000389048,NM_004304.4,7,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,CD246
3,AMER1,139285,ENST00000330258,NM_152424.3,ENST00000374869,NM_152424.3,7,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,"FAM123B, FLJ39827, RP11-403E24.2, WTX"
4,APC,324,ENST00000257430,NM_000038.5,ENST00000257430,NM_000038.5,7,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,"DP2.5, PPP1R46"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061,ZFP36L1,677,ENST00000336440,NM_001244698.1,ENST00000336440,NM_001244698.1,1,Yes,No,Yes,No,No,No,No,No,No,"Berg36, RNF162B, TIS11B, cMG1"
1062,ZMYM3,9203,NaN,NaN,NaN,NaN,1,No,No,No,No,No,No,Yes,No,No,"DXS6673E, KIAA0385, ZNF198L2, ZNF261"
1063,ZNF24,7572,NaN,NaN,NaN,NaN,1,No,No,No,No,No,No,Yes,No,No,"KOX17, ZNF191, ZSCAN3, Zfp191"
1064,ZNF331,55422,NaN,NaN,NaN,NaN,1,No,No,No,No,No,No,No,No,Yes,"RITA, ZNF361, ZNF463"
1065,ZNF750,79755,ENST00000269394,NM_024702.2,ENST00000269394,NM_024702.2,1,Yes,No,Yes,No,No,No,No,No,No,"FLJ13841, Zfp750"

In [44]:
oncokb_genes["OncoKB Annotated"].value_counts()

Yes    688
No     378
Name: OncoKB Annotated, dtype: int64

In [45]:
oncokb_genes["Is Oncogene"].value_counts()

No     765
Yes    301
Name: Is Oncogene, dtype: int64

In [46]:
oncokb_genes["Is Tumor Suppressor Gene"].value_counts()

No     759
Yes    307
Name: Is Tumor Suppressor Gene, dtype: int64

In [47]:
oncokb_annotated_genes = sorted(list(set(overlapping_genes) & set(oncokb_genes[oncokb_genes["OncoKB Annotated"] == "Yes"]["Hugo Symbol"])))
len(oncokb_annotated_genes)

638

In [48]:
# choosing only oncokb annotated genes
mut_csv_oncokb = mut_csv[oncokb_annotated_genes]
cnv_csv_oncokb = cnv_csv[oncokb_annotated_genes]
gene_exp_csv_oncokb = gene_exp_csv[oncokb_annotated_genes]

In [49]:
mut_csv_oncokb.to_csv("../../datasets/NCMF/CellLine/mutations_oncokb.csv")
cnv_csv_oncokb.to_csv("../../datasets/NCMF/CellLine/cnv_oncokb.csv")
gene_exp_csv_oncokb.to_csv("../../datasets/NCMF/CellLine/gene_expression_oncokb.csv")
audrc_csv_binary.to_csv("../../datasets/NCMF/CellLine/audrc_binary.csv")

In [50]:
mut_csv.to_csv("../../datasets/NCMF/CellLine/mutations.csv")
cnv_csv.to_csv("../../datasets/NCMF/CellLine/cnv.csv")
gene_exp_csv.to_csv("../../datasets/NCMF/CellLine/gene_expression.csv")
audrc_csv.to_csv("../../datasets/NCMF/CellLine/audrc.csv")

In [51]:
cell_lines = list(mut_csv.index)
genes = list(mut_csv.columns)
genes_oncokb = list(mut_csv_oncokb.columns)
drugs = list(cellline_drug_auc.columns)
entities = cell_lines + genes + drugs
len(entities)

18603

In [52]:
entities_oncokb = cell_lines + genes_oncokb + drugs
len(entities_oncokb)

1726

In [53]:
entity_df = pd.DataFrame()
entity_df["Entity Names"] = entities
entity_df

      Entity Names
0       ACH-000001
1       ACH-000002
2       ACH-000004
3       ACH-000006
4       ACH-000007
...            ...
18598        ZG-10
18599   ZIBOTENTAN
18600    ZM-447439
18601  ZOLEDRONATE
18602     ZSTK-474

[18603 rows x 1 columns]

In [54]:
entity_df.to_csv("../../datasets/NCMF/CellLine/entity.csv", index=False)

In [55]:
entity_df_oncokb = pd.DataFrame()
entity_df_oncokb["Entity Names"] = entities_oncokb
entity_df_oncokb

     Entity Names
0      ACH-000001
1      ACH-000002
2      ACH-000004
3      ACH-000006
4      ACH-000007
...           ...
1721        ZG-10
1722   ZIBOTENTAN
1723    ZM-447439
1724  ZOLEDRONATE
1725     ZSTK-474

[1726 rows x 1 columns]

In [56]:
entity_df_oncokb.to_csv("../../datasets/NCMF/CellLine/entity_oncokb.csv", index=False)