This notebook takes in a list of matrices as inputs and generates the dat files needed by NCMF. This also involves sampling the target matrix for creation of train and test files as well.

Input given to this notebook:
1. List of matrices
2. Matrix being used by the link prediction task - this will be divided into train and test sets, with the embeddings being learnt from the train set; link prediction is done by a classifier trained on the train dataset and tested on the test set generated. The matrices must be saved as csv files.
3. entity.csv containing all the entity names in the order E0, E1, ... as they appear in the matrices. If a particular node type can be of differing labels(eg: node type is disease, node label is Asthma), this info must be present in a column called "Entity labels" in this csv. If this column is absent, node_label and node_type are considered to be the same.

Output from notebook:
1. sampled#_node.dat
2. sampled#_link.dat
3. sampled#_link.dat.test
4. sampled#_label.dat
5. sampled#_label.dat.test
6. sampled#_meta.dat
7. sampled#_info.dat

This notebook uses the drug-drug, drug-protein and protein-protein interaction matrices of the Polypharmacy experiments to get train-test splits, with test data being from drug-protein interaction matrix.

#### User inputs (Values to be modified as per the dataset)

In [1]:
# Fill out the following values as per the dataset
sample_id = 3 # update sample ID number
data_folder = "../../datasets/NCMF/PolyP3/" # path to the folder with the matrices
all_matrices = ["drug-drug.csv", "drug-protein.csv", "protein-protein.csv"] # provide a comma separated list of file names; each matrix must be mapped to a separate file
entity_mapping = {'X0': ['E0', 'E0'],
                 'X1': ['E0', 'E1'],
                 'X2': ['E1', 'E1']}
entity_name_mapping = {'E0': "drug", "E1": "protein"} # Modify this as per the dataset for all entities
target_matrix_index = 1 # Set this to match the index of the matrix file as per the list all_matrices; this matrix is divided into train and test
rng = 42 # random number seed; edit this to create different samples

#### Output files generated

In [2]:
# Output files
sampled_node_file = data_folder + f'sampled{sample_id}_node.dat'
sampled_link_file = data_folder + f'sampled{sample_id}_link.dat'
sampled_link_test_file = data_folder + f'sampled{sample_id}_link.dat.test'
sampled_label_file = data_folder + f'sampled{sample_id}_label.dat'
sampled_label_test_file = data_folder + f'sampled{sample_id}_label.dat.test'
sampled_meta_file = data_folder + f'sampled{sample_id}_meta.dat'
sampled_info_file = data_folder + f'sampled{sample_id}_info.dat'

#### Data Processing
The following steps are carried out in the section below:
1. Find number of entities in all the matrices and assign unique IDs to each entity
2. Flatten the matrix into a list of triplets
3. From the target_matrix, sample 20% for use as test data
4. Create node.dat, link.dat, link.dat.test, label.dat, label.dat.test, meta.dat for the dataset

In [3]:
import pandas as pd
import numpy as np
import random
random.seed(rng)

In [4]:
for i in range(len(all_matrices)):
    exec(f"X{i} = pd.read_csv(data_folder + all_matrices[i], header = None).to_numpy()")
# This block assigns each of the matrices to variables X0, X1, X2,...

In [5]:
for i in range(len(all_matrices)):
    print(f"Shape of X{i}", end = " ")
    exec(f"print(X{i}.shape)")

Shape of X0 (645, 645)
Shape of X1 (645, 837)
Shape of X2 (837, 837)

In [6]:
# Get entity IDs - uses matrix_entity_similarity to get total number of unique entries
total_entities = 0
matrices_seen = []
for k,v in entity_mapping.items():
    if v[0] not in matrices_seen:
        matrices_seen.append(v[0])
        total_entities += eval(f"{k}.shape[0]")
        exec(f"{v[0]}_size = {k}.shape[0]")
    if v[1] not in matrices_seen:
        matrices_seen.append(v[1])
        total_entities += eval(f"{k}.shape[1]")
        exec(f"{v[1]}_size = {k}.shape[1]")
print(total_entities)

1482

In [7]:
print(E0_size)

645

In [8]:
full_df = pd.DataFrame(columns = ["left", "right", "value", "link_type"])

In [9]:
for k,v in entity_mapping.items(): # iterate over all matrices
    print(f"Considering {k}")
    link_type = int(k[1:])
    total_left_ents_so_far = 0
    for m in matrices_seen:
        if v[0] == m:
            break
        else:
            total_left_ents_so_far += eval(f"{m}_size")
    
    total_right_ents_so_far = 0
    for m in matrices_seen:
        if v[1] == m:
            break
        else:
            total_right_ents_so_far += eval(f"{m}_size")
            
#     for i in range(eval(f"{v[0]}_size")):
#         for j in range(eval(f"{v[1]}_size")):
#             left_id = i + total_left_ents_so_far
#             right_id = j + total_right_ents_so_far
#             value = eval(f"{k}[i][j]")
#             print(f"left = {left_id}, right = {right_id}, value = {value}")
#             full_df = full_df.append({"left": left_id, "right": right_id, "value": value, "link_type": link_type}, ignore_index = True)
    temp_df = pd.DataFrame(columns = ["left", "right", "value", "link_type"])
    temp_df["left"] = sorted(list(range(total_left_ents_so_far, total_left_ents_so_far + eval(f"{v[0]}_size"))) * eval(f"{v[1]}_size"))
    temp_df["right"] = list(range(total_right_ents_so_far, total_right_ents_so_far + eval(f"{v[1]}_size"))) * eval(f"{v[0]}_size")
    temp_df["value"] = eval(f"{k}").flatten()
    temp_df["link_type"] = [link_type] * len(temp_df["left"])
    full_df = pd.concat([full_df, temp_df], axis = 0, ignore_index = True)

Considering X0
Considering X1
Considering X2

In [10]:
full_df.shape

(1656459, 4)

In [11]:
full_df.head()

  left right  value link_type
0    0     0    1.0         0
1    0     1    0.0         0
2    0     2    0.0         0
3    0     3    0.0         0
4    0     4    0.0         0

In [12]:
full_df.tail()

         left right  value link_type
1656454  1481  1477    0.0         2
1656455  1481  1478    0.0         2
1656456  1481  1479    0.0         2
1656457  1481  1480    0.0         2
1656458  1481  1481    0.0         2

In [13]:
full_df.iloc[8]

left         0
right        8
value        1
link_type    0
Name: 8, dtype: object

#### Link file generation

The link.dat.test file is of the format left_node_id, right_node_id, link_value. It has both positive and negative links, and is used to train and test the SVM classifier in the downstream link prediction task.

The link.dat file is of the format left_node_id, right_node_id, link_type, link_value. It is made up of only positive links, i.e link_value is 1. This file is used to learn the embeddings of all the entities in the graph.

In [14]:
np.random.seed(rng)
target_matrix_R_ent_count = eval(f"X{target_matrix_index}.shape[0]")
target_matrix_C_ent_count = eval(f"X{target_matrix_index}.shape[1]")
sample = np.random.choice(target_matrix_R_ent_count * target_matrix_C_ent_count, int(0.2 * target_matrix_R_ent_count * target_matrix_C_ent_count) , replace = False) # sample 20 % of the data

In [15]:
offset = 0
for i in range(target_matrix_index):
    offset += eval(f"X{i}.shape[0] * X{i}.shape[1]")
print(f"Offset for samples is {offset}")

Offset for samples is 416025

In [16]:
sample = sample + offset

In [17]:
sample

array([440220, 875604, 605786, ..., 633913, 729767, 932420])

In [18]:
test_data = full_df.iloc[sample]

In [19]:
orig_test_data_size = test_data.shape[0]

In [20]:
# Find all entries that are zeros in the test df
zero_test_data = pd.DataFrame(test_data.groupby("left").sum()["value"]).reset_index()
zero_test_data = zero_test_data[zero_test_data["value"] == 0]

In [21]:
len(zero_test_data["left"].unique())

457

In [22]:
zero_test_data

     left  value
0       0    0.0
2       2    0.0
3       3    0.0
4       4    0.0
5       5    0.0
..    ...    ...
640   640    0.0
641   641    0.0
642   642    0.0
643   643    0.0
644   644    0.0

[457 rows x 2 columns]

In [23]:
node1_offset = 0
v = entity_mapping[f"X{target_matrix_index}"]
for m in matrices_seen:
    if v[0] == m:
        break
    else:
        node1_offset += eval(f"{m}_size")

In [24]:
node1_offset

0

In [25]:
node2_offset = 0
v = entity_mapping[f"X{target_matrix_index}"]
for m in matrices_seen:
    if v[1] == m:
        break
    else:
        node2_offset += eval(f"{m}_size")

In [26]:
node2_offset

645

In [27]:
for i in list(zero_test_data["left"].unique()):
    x = eval(f"X{target_matrix_index}[{int(i) - node1_offset},:]")
    print(i)
    non_zeros = np.where(x != 0)[0]
    print(non_zeros)            
    node_1 = int(i)
    try:
        node_2 = float(random.choice(non_zeros)) + node2_offset
        print(f"Node 1: {node_1}, Node 2: {node_2}")
        print(f"sample val = {int((node_1 - node1_offset) * target_matrix_R_ent_count) + int(node_2 - node2_offset) + offset}")
        value_added = eval(f"X{target_matrix_index}[{int(i) - node1_offset}][{node_2 - node2_offset}]")
        test_data = test_data.append({"left": node_1, "right": node_2, "value": value_added, "link_type": target_matrix_index}, ignore_index = True)
        sample = np.append(sample, int((node_1 - node1_offset) * target_matrix_R_ent_count) + int(node_2 - node2_offset) + offset)
    except:
        print(f"Cannot find a non zero entry for {node_1}")

0
[]
Cannot find a non zero entry for 0
2
[]
Cannot find a non zero entry for 2
3
[]
Cannot find a non zero entry for 3
4
[]
Cannot find a non zero entry for 4
5
[]
Cannot find a non zero entry for 5
6
[]
Cannot find a non zero entry for 6
7
[]
Cannot find a non zero entry for 7
9
[]
Cannot find a non zero entry for 9
11
[]
Cannot find a non zero entry for 11
12
[]
Cannot find a non zero entry for 12
14
[]
Cannot find a non zero entry for 14
15
[]
Cannot find a non zero entry for 15
16
[]
Cannot find a non zero entry for 16
17
[]
Cannot find a non zero entry for 17
18
[]
Cannot find a non zero entry for 18
20
[]
Cannot find a non zero entry for 20
21
[]
Cannot find a non zero entry for 21
24
[226 228 266 280 340 348 351 353]
Node 1: 24, Node 2: 873.0
sample val = 431733
Cannot find a non zero entry for 24
25
[164]
Node 1: 25, Node 2: 809.0
sample val = 432314
Cannot find a non zero entry for 25
26
[]
Cannot find a non zero entry for 26
27
[]
Cannot find a non zero entry for 27
28
[]
Cannot find a non zero entry for 28
30
[]
Cannot find a non zero entry for 30
31
[]
Cannot find a non zero entry for 31
32
[]
Cannot find a non zero entry for 32
33
[175 574]
Node 1: 33, Node 2: 1219.0
sample val = 437884
Cannot find a non zero entry for 33
34
[]
Cannot find a non zero entry for 34
35
[]
Cannot find a non zero entry for 35
38
[227 234 260 268 269 270 274 275 313 323 337 356 401 404 418 468]
Node 1: 38, Node 2: 920.0
sample val = 440810
Cannot find a non zero entry for 38
39
[]
Cannot find a non zero entry for 39
40
[]
Cannot find a non zero entry for 40
45
[]
Cannot find a non zero entry for 45
46
[403]
Node 1: 46, Node 2: 1048.0
sample val = 446098
Cannot find a non zero entry for 46
47
[8]
Node 1: 47, Node 2: 653.0
sample val = 446348
Cannot find a non zero entry for 47
48
[]
Cannot find a non zero entry for 48
52
[  4   6 176 429]
Node 1: 52, Node 2: 649.0
sample val = 449569
Cannot find a non zero entry for 52
54
[]
Cannot find a non zero entry for 54
55
[]
Cannot find a non zero entry for 55
56
[]
Cannot find a non zero entry for 56
57
[]
Cannot find a non zero entry for 57
58
[237]
Node 1: 58, Node 2: 882.0
sample val = 453672
Cannot find a non zero entry for 58
60
[]
Cannot find a non zero entry for 60
63
[]
Cannot find a non zero entry for 63
64
[]
Cannot find a non zero entry for 64
65
[]
Cannot find a non zero entry for 65
67
[]
Cannot find a non zero entry for 67
68
[]
Cannot find a non zero entry for 68
69
[]
Cannot find a non zero entry for 69
70
[14]
Node 1: 70, Node 2: 659.0
sample val = 461189
Cannot find a non zero entry for 70
71
[]
Cannot find a non zero entry for 71
72
[]
Cannot find a non zero entry for 72
73
[]
Cannot find a non zero entry for 73
75
[158 160 161 163 164 165]
Node 1: 75, Node 2: 803.0
sample val = 464558
Cannot find a non zero entry for 75
77
[13 21]
Node 1: 77, Node 2: 658.0
sample val = 465703
Cannot find a non zero entry for 77
79
[]
Cannot find a non zero entry for 79
80
[]
Cannot find a non zero entry for 80
81
[167 168]
Node 1: 81, Node 2: 812.0
sample val = 468437
Cannot find a non zero entry for 81
84
[]
Cannot find a non zero entry for 84
85
[]
Cannot find a non zero entry for 85
86
[]
Cannot find a non zero entry for 86
89
[]
Cannot find a non zero entry for 89
90
[]
Cannot find a non zero entry for 90
92
[]
Cannot find a non zero entry for 92
94
[]
Cannot find a non zero entry for 94
95
[]
Cannot find a non zero entry for 95
96
[]
Cannot find a non zero entry for 96
98
[]
Cannot find a non zero entry for 98
99
[]
Cannot find a non zero entry for 99
100
[]
Cannot find a non zero entry for 100
101
[]
Cannot find a non zero entry for 101
102
[]
Cannot find a non zero entry for 102
103
[]
Cannot find a non zero entry for 103
104
[]
Cannot find a non zero entry for 104
105
[]
Cannot find a non zero entry for 105
106
[]
Cannot find a non zero entry for 106
107
[]
Cannot find a non zero entry for 107
109
[]
Cannot find a non zero entry for 109
110
[]
Cannot find a non zero entry for 110
111
[]
Cannot find a non zero entry for 111
112
[]
Cannot find a non zero entry for 112
113
[158]
Node 1: 113, Node 2: 803.0
sample val = 489068
Cannot find a non zero entry for 113
114
[]
Cannot find a non zero entry for 114
116
[]
Cannot find a non zero entry for 116
117
[167 809]
Node 1: 117, Node 2: 812.0
sample val = 491657
Cannot find a non zero entry for 117
118
[]
Cannot find a non zero entry for 118
121
[]
Cannot find a non zero entry for 121
123
[615 661]
Node 1: 123, Node 2: 1260.0
sample val = 495975
Cannot find a non zero entry for 123
124
[]
Cannot find a non zero entry for 124
128
[]
Cannot find a non zero entry for 128
129
[]
Cannot find a non zero entry for 129
131
[]
Cannot find a non zero entry for 131
133
[]
Cannot find a non zero entry for 133
136
[]
Cannot find a non zero entry for 136
137
[]
Cannot find a non zero entry for 137
138
[]
Cannot find a non zero entry for 138
139
[]
Cannot find a non zero entry for 139
140
[]
Cannot find a non zero entry for 140
141
[]
Cannot find a non zero entry for 141
142
[12]
Node 1: 142, Node 2: 657.0
sample val = 507627
Cannot find a non zero entry for 142
143
[]
Cannot find a non zero entry for 143
144
[]
Cannot find a non zero entry for 144
146
[]
Cannot find a non zero entry for 146
148
[]
Cannot find a non zero entry for 148
151
[]
Cannot find a non zero entry for 151
153
[]
Cannot find a non zero entry for 153
155
[]
Cannot find a non zero entry for 155
157
[]
Cannot find a non zero entry for 157
159
[403]
Node 1: 159, Node 2: 1048.0
sample val = 518983
Cannot find a non zero entry for 159
161
[239]
Node 1: 161, Node 2: 884.0
sample val = 520109
Cannot find a non zero entry for 161
162
[]
Cannot find a non zero entry for 162
165
[]
Cannot find a non zero entry for 165
168
[]
Cannot find a non zero entry for 168
171
[]
Cannot find a non zero entry for 171
172
[]
Cannot find a non zero entry for 172
173
[]
Cannot find a non zero entry for 173
174
[]
Cannot find a non zero entry for 174
175
[]
Cannot find a non zero entry for 175
177
[]
Cannot find a non zero entry for 177
178
[]
Cannot find a non zero entry for 178
179
[]
Cannot find a non zero entry for 179
180
[226 228]
Node 1: 180, Node 2: 873.0
sample val = 532353
Cannot find a non zero entry for 180
181
[]
Cannot find a non zero entry for 181
182
[]
Cannot find a non zero entry for 182
184
[14]
Node 1: 184, Node 2: 659.0
sample val = 534719
Cannot find a non zero entry for 184
187
[158 167]
Node 1: 187, Node 2: 803.0
sample val = 536798
Cannot find a non zero entry for 187
188
[]
Cannot find a non zero entry for 188
189
[167 429]
Node 1: 189, Node 2: 812.0
sample val = 538097
Cannot find a non zero entry for 189
190
[]
Cannot find a non zero entry for 190
191
[]
Cannot find a non zero entry for 191
193
[]
Cannot find a non zero entry for 193
194
[]
Cannot find a non zero entry for 194
195
[]
Cannot find a non zero entry for 195
196
[]
Cannot find a non zero entry for 196
197
[]
Cannot find a non zero entry for 197
198
[369 619 639]
Node 1: 198, Node 2: 1284.0
sample val = 544374
Cannot find a non zero entry for 198
200
[]
Cannot find a non zero entry for 200
202
[173]
Node 1: 202, Node 2: 818.0
sample val = 546488
Cannot find a non zero entry for 202
203
[]
Cannot find a non zero entry for 203
205
[]
Cannot find a non zero entry for 205
208
[]
Cannot find a non zero entry for 208
210
[811]
Node 1: 210, Node 2: 1456.0
sample val = 552286
Cannot find a non zero entry for 210
211
[]
Cannot find a non zero entry for 211
212
[]
Cannot find a non zero entry for 212
213
[]
Cannot find a non zero entry for 213
214
[175 230 247 297 581]
Node 1: 214, Node 2: 892.0
sample val = 554302
Cannot find a non zero entry for 214
215
[]
Cannot find a non zero entry for 215
216
[]
Cannot find a non zero entry for 216
217
[169]
Node 1: 217, Node 2: 814.0
sample val = 556159
Cannot find a non zero entry for 217
219
[160 161 163 164 165]
Node 1: 219, Node 2: 806.0
sample val = 557441
Cannot find a non zero entry for 219
221
[]
Cannot find a non zero entry for 221
223
[]
Cannot find a non zero entry for 223
224
[]
Cannot find a non zero entry for 224
226
[]
Cannot find a non zero entry for 226
227
[]
Cannot find a non zero entry for 227
228
[]
Cannot find a non zero entry for 228
229
[]
Cannot find a non zero entry for 229
230
[227]
Node 1: 230, Node 2: 872.0
sample val = 564602
Cannot find a non zero entry for 230
231
[158]
Node 1: 231, Node 2: 803.0
sample val = 565178
Cannot find a non zero entry for 231
232
[  0 158 160 161 163 164 165]
Node 1: 232, Node 2: 645.0
sample val = 565665
Cannot find a non zero entry for 232
233
[226 228 266 280 340 348 351 353]
Node 1: 233, Node 2: 996.0
sample val = 566661
Cannot find a non zero entry for 233
236
[]
Cannot find a non zero entry for 236
239
[]
Cannot find a non zero entry for 239
241
[]
Cannot find a non zero entry for 241
242
[]
Cannot find a non zero entry for 242
243
[]
Cannot find a non zero entry for 243
244
[]
Cannot find a non zero entry for 244
245
[]
Cannot find a non zero entry for 245
248
[]
Cannot find a non zero entry for 248
249
[]
Cannot find a non zero entry for 249
251
[]
Cannot find a non zero entry for 251
252
[429]
Node 1: 252, Node 2: 1074.0
sample val = 578994
Cannot find a non zero entry for 252
253
[]
Cannot find a non zero entry for 253
254
[]
Cannot find a non zero entry for 254
255
[]
Cannot find a non zero entry for 255
260
[]
Cannot find a non zero entry for 260
262
[168 190]
Node 1: 262, Node 2: 835.0
sample val = 585205
Cannot find a non zero entry for 262
263
[]
Cannot find a non zero entry for 263
264
[225]
Node 1: 264, Node 2: 870.0
sample val = 586530
Cannot find a non zero entry for 264
266
[]
Cannot find a non zero entry for 266
267
[]
Cannot find a non zero entry for 267
268
[]
Cannot find a non zero entry for 268
269
[]
Cannot find a non zero entry for 269
270
[272]
Node 1: 270, Node 2: 917.0
sample val = 590447
Cannot find a non zero entry for 270
272
[  2 158 163 167 176 190]
Node 1: 272, Node 2: 647.0
sample val = 591467
Cannot find a non zero entry for 272
273
[]
Cannot find a non zero entry for 273
275
[]
Cannot find a non zero entry for 275
281
[]
Cannot find a non zero entry for 281
282
[]
Cannot find a non zero entry for 282
283
[691]
Node 1: 283, Node 2: 1336.0
sample val = 599251
Cannot find a non zero entry for 283
285
[]
Cannot find a non zero entry for 285
286
[]
Cannot find a non zero entry for 286
287
[]
Cannot find a non zero entry for 287
289
[]
Cannot find a non zero entry for 289
290
[]
Cannot find a non zero entry for 290
291
[]
Cannot find a non zero entry for 291
294
[]
Cannot find a non zero entry for 294
298
[]
Cannot find a non zero entry for 298
301
[169 593]
Node 1: 301, Node 2: 814.0
sample val = 610339
Cannot find a non zero entry for 301
302
[]
Cannot find a non zero entry for 302
303
[]
Cannot find a non zero entry for 303
304
[]
Cannot find a non zero entry for 304
306
[ 12 162 166]
Node 1: 306, Node 2: 807.0
sample val = 613557
Cannot find a non zero entry for 306
308
[162 166]
Node 1: 308, Node 2: 807.0
sample val = 614847
Cannot find a non zero entry for 308
309
[]
Cannot find a non zero entry for 309
310
[]
Cannot find a non zero entry for 310
311
[]
Cannot find a non zero entry for 311
313
[]
Cannot find a non zero entry for 313
314
[]
Cannot find a non zero entry for 314
315
[]
Cannot find a non zero entry for 315
316
[]
Cannot find a non zero entry for 316
319
[]
Cannot find a non zero entry for 319
320
[]
Cannot find a non zero entry for 320
321
[ 14 169 175 176 375]
Node 1: 321, Node 2: 1020.0
sample val = 623445
Cannot find a non zero entry for 321
325
[]
Cannot find a non zero entry for 325
326
[]
Cannot find a non zero entry for 326
327
[489]
Node 1: 327, Node 2: 1134.0
sample val = 627429
Cannot find a non zero entry for 327
328
[]
Cannot find a non zero entry for 328
329
[]
Cannot find a non zero entry for 329
330
[]
Cannot find a non zero entry for 330
331
[]
Cannot find a non zero entry for 331
333
[]
Cannot find a non zero entry for 333
334
[]
Cannot find a non zero entry for 334
336
[176]
Node 1: 336, Node 2: 821.0
sample val = 632921
Cannot find a non zero entry for 336
338
[]
Cannot find a non zero entry for 338
340
[]
Cannot find a non zero entry for 340
341
[]
Cannot find a non zero entry for 341
342
[]
Cannot find a non zero entry for 342
344
[]
Cannot find a non zero entry for 344
346
[]
Cannot find a non zero entry for 346
347
[]
Cannot find a non zero entry for 347
348
[]
Cannot find a non zero entry for 348
349
[]
Cannot find a non zero entry for 349
350
[]
Cannot find a non zero entry for 350
351
[176 403]
Node 1: 351, Node 2: 821.0
sample val = 642596
Cannot find a non zero entry for 351
352
[]
Cannot find a non zero entry for 352
353
[162]
Node 1: 353, Node 2: 807.0
sample val = 643872
Cannot find a non zero entry for 353
354
[]
Cannot find a non zero entry for 354
355
[]
Cannot find a non zero entry for 355
357
[]
Cannot find a non zero entry for 357
358
[]
Cannot find a non zero entry for 358
359
[]
Cannot find a non zero entry for 359
361
[162 166]
Node 1: 361, Node 2: 807.0
sample val = 649032
Cannot find a non zero entry for 361
362
[]
Cannot find a non zero entry for 362
363
[160]
Node 1: 363, Node 2: 805.0
sample val = 650320
Cannot find a non zero entry for 363
366
[]
Cannot find a non zero entry for 366
367
[]
Cannot find a non zero entry for 367
368
[]
Cannot find a non zero entry for 368
369
[]
Cannot find a non zero entry for 369
370
[]
Cannot find a non zero entry for 370
371
[]
Cannot find a non zero entry for 371
373
[]
Cannot find a non zero entry for 373
374
[]
Cannot find a non zero entry for 374
375
[]
Cannot find a non zero entry for 375
376
[583 620]
Node 1: 376, Node 2: 1265.0
sample val = 659165
Cannot find a non zero entry for 376
379
[]
Cannot find a non zero entry for 379
382
[227]
Node 1: 382, Node 2: 872.0
sample val = 662642
Cannot find a non zero entry for 382
386
[]
Cannot find a non zero entry for 386
388
[]
Cannot find a non zero entry for 388
389
[5 8]
Node 1: 389, Node 2: 650.0
sample val = 666935
Cannot find a non zero entry for 389
391
[]
Cannot find a non zero entry for 391
393
[]
Cannot find a non zero entry for 393
394
[]
Cannot find a non zero entry for 394
395
[]
Cannot find a non zero entry for 395
398
[]
Cannot find a non zero entry for 398
399
[]
Cannot find a non zero entry for 399
404
[]
Cannot find a non zero entry for 404
406
[]
Cannot find a non zero entry for 406
407
[]
Cannot find a non zero entry for 407
408
[]
Cannot find a non zero entry for 408
409
[159 162 166]
Node 1: 409, Node 2: 804.0
sample val = 679989
Cannot find a non zero entry for 409
410
[ 20  25 167 673 773 805]
Node 1: 410, Node 2: 1318.0
sample val = 681148
Cannot find a non zero entry for 410
411
[]
Cannot find a non zero entry for 411
412
[]
Cannot find a non zero entry for 412
415
[]
Cannot find a non zero entry for 415
417
[]
Cannot find a non zero entry for 417
418
[]
Cannot find a non zero entry for 418
420
[]
Cannot find a non zero entry for 420
421
[]
Cannot find a non zero entry for 421
422
[]
Cannot find a non zero entry for 422
423
[181 205 210]
Node 1: 423, Node 2: 850.0
sample val = 689065
Cannot find a non zero entry for 423
424
[]
Cannot find a non zero entry for 424
425
[]
Cannot find a non zero entry for 425
427
[]
Cannot find a non zero entry for 427
428
[]
Cannot find a non zero entry for 428
429
[]
Cannot find a non zero entry for 429
430
[]
Cannot find a non zero entry for 430
431
[231]
Node 1: 431, Node 2: 876.0
sample val = 694251
Cannot find a non zero entry for 431
433
[]
Cannot find a non zero entry for 433
435
[]
Cannot find a non zero entry for 435
437
[]
Cannot find a non zero entry for 437
439
[]
Cannot find a non zero entry for 439
440
[]
Cannot find a non zero entry for 440
441
[]
Cannot find a non zero entry for 441
442
[]
Cannot find a non zero entry for 442
443
[]
Cannot find a non zero entry for 443
445
[]
Cannot find a non zero entry for 445
448
[]
Cannot find a non zero entry for 448
449
[]
Cannot find a non zero entry for 449
450
[]
Cannot find a non zero entry for 450
451
[158 160 161 163 164 165]
Node 1: 451, Node 2: 810.0
sample val = 707085
Cannot find a non zero entry for 451
455
[]
Cannot find a non zero entry for 455
456
[]
Cannot find a non zero entry for 456
457
[]
Cannot find a non zero entry for 457
458
[]
Cannot find a non zero entry for 458
459
[]
Cannot find a non zero entry for 459
461
[]
Cannot find a non zero entry for 461
463
[]
Cannot find a non zero entry for 463
464
[]
Cannot find a non zero entry for 464
465
[]
Cannot find a non zero entry for 465
466
[]
Cannot find a non zero entry for 466
467
[]
Cannot find a non zero entry for 467
468
[227 234 260 268 269 270 274 275 313 323 595]
Node 1: 468, Node 2: 915.0
sample val = 718155
Cannot find a non zero entry for 468
469
[]
Cannot find a non zero entry for 469
470
[]
Cannot find a non zero entry for 470
471
[]
Cannot find a non zero entry for 471
472
[]
Cannot find a non zero entry for 472
474
[]
Cannot find a non zero entry for 474
475
[]
Cannot find a non zero entry for 475
476
[]
Cannot find a non zero entry for 476
477
[]
Cannot find a non zero entry for 477
478
[]
Cannot find a non zero entry for 478
479
[]
Cannot find a non zero entry for 479
480
[]
Cannot find a non zero entry for 480
482
[]
Cannot find a non zero entry for 482
483
[]
Cannot find a non zero entry for 483
484
[]
Cannot find a non zero entry for 484
485
[]
Cannot find a non zero entry for 485
486
[]
Cannot find a non zero entry for 486
487
[]
Cannot find a non zero entry for 487
488
[]
Cannot find a non zero entry for 488
490
[]
Cannot find a non zero entry for 490
491
[]
Cannot find a non zero entry for 491
492
[]
Cannot find a non zero entry for 492
493
[]
Cannot find a non zero entry for 493
495
[]
Cannot find a non zero entry for 495
496
[]
Cannot find a non zero entry for 496
498
[]
Cannot find a non zero entry for 498
499
[]
Cannot find a non zero entry for 499
501
[]
Cannot find a non zero entry for 501
502
[]
Cannot find a non zero entry for 502
503
[]
Cannot find a non zero entry for 503
504
[]
Cannot find a non zero entry for 504
505
[]
Cannot find a non zero entry for 505
506
[]
Cannot find a non zero entry for 506
509
[]
Cannot find a non zero entry for 509
511
[]
Cannot find a non zero entry for 511
512
[]
Cannot find a non zero entry for 512
513
[]
Cannot find a non zero entry for 513
514
[]
Cannot find a non zero entry for 514
515
[]
Cannot find a non zero entry for 515
516
[]
Cannot find a non zero entry for 516
517
[]
Cannot find a non zero entry for 517
519
[24 26 32]
Node 1: 519, Node 2: 669.0
sample val = 750804
Cannot find a non zero entry for 519
520
[]
Cannot find a non zero entry for 520
521
[]
Cannot find a non zero entry for 521
522
[181 205 210]
Node 1: 522, Node 2: 850.0
sample val = 752920
Cannot find a non zero entry for 522
523
[]
Cannot find a non zero entry for 523
524
[237]
Node 1: 524, Node 2: 882.0
sample val = 754242
Cannot find a non zero entry for 524
525
[]
Cannot find a non zero entry for 525
526
[]
Cannot find a non zero entry for 526
527
[]
Cannot find a non zero entry for 527
528
[]
Cannot find a non zero entry for 528
530
[]
Cannot find a non zero entry for 530
531
[]
Cannot find a non zero entry for 531
532
[]
Cannot find a non zero entry for 532
533
[]
Cannot find a non zero entry for 533
535
[]
Cannot find a non zero entry for 535
536
[]
Cannot find a non zero entry for 536
537
[]
Cannot find a non zero entry for 537
538
[734]
Node 1: 538, Node 2: 1379.0
sample val = 763769
Cannot find a non zero entry for 538
539
[]
Cannot find a non zero entry for 539
540
[]
Cannot find a non zero entry for 540
541
[]
Cannot find a non zero entry for 541
542
[]
Cannot find a non zero entry for 542
546
[]
Cannot find a non zero entry for 546
547
[]
Cannot find a non zero entry for 547
550
[158 160 161 163 164 165]
Node 1: 550, Node 2: 810.0
sample val = 770940
Cannot find a non zero entry for 550
551
[]

In [28]:
sample[orig_test_data_size:]

array([], dtype=int64)

In [29]:
test_data["value"] = test_data["value"].apply(lambda x: 1 if x != 0 else 0) # convert value to indicate only presence/absence of link

/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [30]:
test_data.head()

       left right  value link_type
440220   28  1404      0         1
875604  549   711      0         1
605786  226  1244      0         1
580621  196  1189      0         1
736952  383  1001      0         1

In [31]:
test_data.shape[0]

107973

In [32]:
test_data_np = test_data.to_numpy()

In [33]:
print(f"Percentage of ones in test data = {np.count_nonzero(test_data_np[:,2])/test_data_np.shape[0]}")
print(f"Percentage of zeros in test data = {1-(np.count_nonzero(test_data_np[:,2])/test_data_np.shape[0])}")

Percentage of ones in test data = 0.028368203161901587
Percentage of zeros in test data = 0.9716317968380984

In [34]:
# Create link.dat.test
link_file_for_lp = open(sampled_link_test_file, "w+") # Same test file will be used by HIN2Vec and other algorithms too

number_of_pairs = 0
for i in range(test_data_np.shape[0]):
        number_of_pairs += 1
        link_file_for_lp.write(str(int(test_data_np[i][0])) + "\t" + str(int(test_data_np[i][1])) + "\t" + str(int(test_data_np[i][2])) + "\n")
            
link_file_for_lp.close()

In [35]:
full_df.drop(sample, inplace = True, axis = 0)

In [36]:
full_df.shape

(1548486, 4)

In [37]:
# Create link.dat file
emb_df = full_df[full_df["value"] != 0]
emb_df["value"] = emb_df["value"]
emb_df["left"] = emb_df["left"].astype(int)
emb_df["right"] = emb_df["right"].astype(int)
emb_df["link_type"] = emb_df["link_type"].astype(int)
emb_df = emb_df[["left", "right", "link_type", "value"]]
emb_df.head()

/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    left  right  link_type  value
0      0      0          0    1.0
6      0      6          0    1.0
8      0      8          0    1.0
10     0     10          0    1.0
17     0     17          0    1.0

In [38]:
emb_df.to_csv(sampled_link_file, sep="\t", header=False, index=False)

#### Label files generation

The label.dat file has the following format: node_id, node_name, node_type, node_label.

The file label.dat.test has the following format: node_id, node_name, node_type, node_label

In [39]:
entity_file = data_folder + "entity.csv"

In [40]:
entity_df = pd.read_csv(entity_file)

In [41]:
entity_df.head()

   Entity Names
0  CID000000085
1  CID000000119
2  CID000000143
3  CID000000158
4  CID000000159

In [42]:
entity_df.shape

(1482, 1)

In [43]:
matrices_seen # this is the list of entities in the dataset

['E0', 'E1']

In [44]:
if "Entity labels" in entity_df.columns:
    isNodeLabelSeparate = True
    print("Node labels are different from node types")
else:
    isNodeLabelSeparate = False
    print("Node labels are the same as node types")

Node labels are the same as node types

In [45]:
count = 0
node_type = []
node_label = []
for entity in matrices_seen:
    print(f"Entity {entity}")
    entity_size = eval(f"{entity}_size")
    node_type_val = int(entity[1:])
    node_type.extend([node_type_val] * entity_size)
    if not isNodeLabelSeparate:
        node_label.extend([node_type_val] * entity_size)
    count += entity_size
    
entity_df["Node label"] = node_label if not isNodeLabelSeparate else list(entity_df["Entity Labels"])
entity_df["Node type"] = node_type

Entity E0
Entity E1

In [46]:
entity_df.head()

   Entity Names  Node label  Node type
0  CID000000085           0          0
1  CID000000119           0          0
2  CID000000143           0          0
3  CID000000158           0          0
4  CID000000159           0          0

In [47]:
entity_df.tail()

     Entity Names  Node label  Node type
1477        84816           1          1
1478         4190           1          1
1479        92483           1          1
1480        10988           1          1
1481       221656           1          1

In [48]:
test_labels_df = entity_df.sample(frac = 0.2, replace = False, random_state = rng)
test_labels_df = test_labels_df[["Entity Names", "Node type", "Node label"]]
test_labels_df.head()

      Entity Names  Node type  Node label
123   CID000002733          0           0
432   CID000005454          0           0
1031          1146          1           1
529   CID000060795          0           0
1415         64146          1           1

In [49]:
test_labels_df.shape

(296, 3)

In [50]:
remaining_labels_df = entity_df.drop(test_labels_df.index)
remaining_labels_df = remaining_labels_df[["Entity Names", "Node type", "Node label"]]
remaining_labels_df.head()

   Entity Names  Node type  Node label
0  CID000000085          0           0
1  CID000000119          0           0
2  CID000000143          0           0
3  CID000000158          0           0
4  CID000000159          0           0

In [51]:
remaining_labels_df.shape

(1186, 3)

In [52]:
test_labels_df.to_csv(sampled_label_test_file, sep = "\t", header = False)

In [53]:
remaining_labels_df.to_csv(sampled_label_file, sep = "\t", header = False)

#### Node file generation

Node file node.dat is of the format node id, node_name, node_type.

In [54]:
entity_df[["Entity Names", "Node type"]].to_csv(sampled_node_file, sep = "\t", header = False)

#### Meta file generation
This file is of the format

Node Total: Count <total number of entities>
Node Type_0: Count <E0_size>
...
Edge Total: Count <total number of links>
Edge Type_0: Count <number of positive links in E0>
...
Label Total: Count <total number of node label types>
Label Class_0_Total: Count <total number of nodes in E0>
Label Class_0_Type_0: Count <total number of nodes in E0 of label 0>
...

In [55]:
# Getting node counts
node_values = list(entity_df.groupby("Node type").count()["Entity Names"])
print(node_values)

[645, 837]

In [56]:
# Getting link counts
emb_count = list(emb_df.groupby("link_type").count()["value"])
test_count = list(test_data[test_data["value"] != 0].groupby("link_type").count()['value'])[0]
emb_count[target_matrix_index] += test_count
print(emb_count)

[127591, 15575, 20298]

In [57]:
# Getting label counts
entity_df.groupby(["Node type", "Node label"]).count()

                      Entity Names
Node type Node label
0         0                    645
1         1                    837

In [58]:
label_counts = entity_df.groupby(['Node type','Node label']).count().apply(list).to_dict()
print(label_counts)

{'Entity Names': {(0, 0): 645, (1, 1): 837}}

In [59]:
meta_file_writer = open(sampled_meta_file, "w+")

meta_file_writer.write(f"Node Total: Count {sum(node_values)}" + "\n")
for i in range(len(node_values)):
    meta_file_writer.write(f"Node Type_{i}: Count {node_values[i]}" + "\n")
meta_file_writer.write(f"Edge Total: Count {sum(emb_count)}" + "\n")
for i in range(len(emb_count)):
    meta_file_writer.write(f"Edge Type_{i}: Count {emb_count[i]}" + "\n")
meta_file_writer.write(f"Label Total: Count {sum(label_counts['Entity Names'].values())}" + "\n")

for i in range(len(node_values)):
    meta_file_writer.write(f"Label Class_{i}_Total: Count {node_values[i]}" + "\n")
    for k in sorted(label_counts["Entity Names"]):
        if k[0] == i:
            meta_file_writer.write(f"Label Class_{k[0]}_Type_{k[1]}: Count {label_counts['Entity Names'][k]}" + "\n")
        
meta_file_writer.close()

#### Info file generation

Info file is of the format

node.dat

TYPE    MEANING

0       DRUG

1       PROTEIN

-----------------------------------------------

link.dat

LINK    START   END     MEANING

0       0       0       DRUG-and-DRUG

1       0       1       DRUG-and-PROTEIN

2       1       1       PROTEIN-and-PROTEIN

-----------------------------------------------

label.dat

TYPE    CLASS   MEANING

0       0       DRUG

1       1       PROTEIN

In [60]:
info_file_writer = open(sampled_info_file, "w+")

info_file_writer.write("node.dat\n")
info_file_writer.write("TYPE\tMEANING\n")
for k, v in entity_name_mapping.items():
    info_file_writer.write(f"{k[1:]}"+"\t"+f"{v}"+"\n")

info_file_writer.write("\n-----------------------------------------------\n")

info_file_writer.write("link.dat\n")
info_file_writer.write("LINK\tSTART\tEND\tMEANING\n")
for k,v in entity_mapping.items():
    info_file_writer.write(f"{k[1:]}" + "\t" + f"{v[0][1:]}" + "\t" + f"{v[1][1:]}" + "\t" + f"{entity_name_mapping[f'E{int(v[0][1:])}']}" + "-and-" + f"{entity_name_mapping[f'E{int(v[1][1:])}']}" + "\n")

info_file_writer.write("\n-----------------------------------------------\n")
info_file_writer.write("label.dat\n")
info_file_writer.write("TYPE\tCLASS\tMEANING\n")
for i in range(len(node_values)):
    for k in sorted(label_counts["Entity Names"]):
        if k[0] == i:
            info_file_writer.write(f"{i}" + "\t" + f"{k[1]}" + "\t" + f"{entity_name_mapping[f'E{int(k[1])}']}" + "\n")

info_file_writer.close()