In [1]:
import numpy as np
import pandas as pd
import os
from datetime import datetime
import time
import random
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import pickle as pkl

In [2]:
data_dir = "./ncmf_sim_data"

In [3]:
#NCMF
out_dir_base_ncmf = data_dir + "/"
fname_ncmf = out_dir_base_ncmf+"dict_perf_ncmf.pkl"
#DFMF
out_dir_base_dfmf = data_dir + "/dfmf/out/"
fname_dfmf = out_dir_base_dfmf+"dict_perf_dfmf.pkl"
#DCMF
out_dir_base_dcmf = data_dir + "/dcmf/out/"
fname_dcmf = out_dir_base_dcmf+"dict_perf_dcmf.pkl"
#CMF
out_dir_base_cmf = data_dir + "/cmf/out/"
fname_cmf = out_dir_base_cmf+"dict_perf_cmf.pkl"
#gCMF
out_dir_base_gcmf = data_dir + "/gcmf/out/"
fname_gcmf = out_dir_base_gcmf+"dict_perf_gcmf.pkl"

In [4]:
dict_perf_ncmf = pkl.load(open(fname_ncmf,"rb"))
dict_perf_dfmf = pkl.load(open(fname_dfmf,"rb"))
dict_perf_dcmf = pkl.load(open(fname_dcmf,"rb"))
dict_perf_cmf = pkl.load(open(fname_cmf,"rb"))
dict_perf_gcmf = pkl.load(open(fname_gcmf,"rb"))

In [5]:
df_perf_ncmf = pd.DataFrame(dict_perf_ncmf)
df_perf_dfmf = pd.DataFrame(dict_perf_dfmf)
df_perf_dcmf = pd.DataFrame(dict_perf_dcmf)
df_perf_cmf = pd.DataFrame(dict_perf_cmf)
df_perf_gcmf = pd.DataFrame(dict_perf_gcmf)

In [6]:
dict_result = {}
mat_id_mse = 0
mat_id_auc = 2
#
dict_mse = {}
dict_auc = {}
for idx,row in df_perf_ncmf.T.iterrows():
    dict_mse[idx] = row[mat_id_mse]["perf"]
    dict_auc[idx] = row[mat_id_auc]["perf"]
dict_result["ncmf"] = {"mse":dict_mse, "auc":dict_auc}
#
dict_mse = {}
dict_auc = {}
for idx,row in df_perf_dfmf.T.iterrows():
    dict_mse[idx] = row[mat_id_mse]["perf"]
    dict_auc[idx] = row[mat_id_auc]["perf"]
dict_result["dfmf"] = {"mse":dict_mse, "auc":dict_auc}
#
dict_mse = {}
dict_auc = {}
for idx,row in df_perf_dcmf.T.iterrows():
    dict_mse[idx] = row[mat_id_mse]["perf"]
    dict_auc[idx] = row[mat_id_auc]["perf"]
dict_result["dcmf"] = {"mse":dict_mse, "auc":dict_auc}
#
dict_mse = {}
dict_auc = {}
for idx,row in df_perf_cmf.T.iterrows():
    dict_mse[idx] = row[mat_id_mse]["perf"]
    dict_auc[idx] = row[mat_id_auc]["perf"]
dict_result["cmf"] = {"mse":dict_mse, "auc":dict_auc}
#
dict_mse = {}
dict_auc = {}
for idx,row in df_perf_gcmf.T.iterrows():
    dict_mse[idx] = row[mat_id_mse]["perf"]
    dict_auc[idx] = row[mat_id_auc]["perf"]
dict_result["gcmf"] = {"mse":dict_mse, "auc":dict_auc}

In [7]:
dict_result

{'ncmf': {'mse': {'dt1': 0.1637057220713486,
   'ds1': 0.1437824265778871,
   'ds2': 0.15189005574930126,
   'ds3': 0.16032868005873901,
   'dn1': 0.16099945242087765,
   'dn2': 0.16518010762495147,
   'dn3': 0.1603969991481468},
  'auc': {'dt1': 0.5600723885408575,
   'ds1': 0.4810386743668927,
   'ds2': 0.5850116958482698,
   'ds3': 0.5635791892600134,
   'dn1': 0.5380906564756995,
   'dn2': 0.505592427665052,
   'dn3': 0.5276289846072463}},
 'dfmf': {'mse': {'dt1': 0.3407051297747372,
   'ds1': 0.35980668572906727,
   'ds2': 0.34750126361068334,
   'ds3': 0.3329534752850991,
   'dn1': 0.3413050905630841,
   'dn2': 0.3401056611358569,
   'dn3': 0.3438802710685656},
  'auc': {'dt1': 0.4990245533615193,
   'ds1': 0.5007997598302284,
   'ds2': 0.48782246773719035,
   'ds3': 0.4896867698954209,
   'dn1': 0.5031146978636207,
   'dn2': 0.5091870245978096,
   'dn3': 0.49576112310553655}},
 'dcmf': {'mse': {'dt1': 0.28542420466628426,
   'ds1': 0.3038139478407574,
   'ds2': 0.20960065673399408,
   'ds3': 0.22119480300710248,
   'dn1': 0.2873992495320662,
   'dn2': 0.3109104846903612,
   'dn3': 0.2996956088044357},
  'auc': {'dt1': 0.6383394539406986,
   'ds1': 0.5015384234480312,
   'ds2': 0.452979275830371,
   'ds3': 0.1766540410526446,
   'dn1': 0.540039077350919,
   'dn2': 0.5124847144976513,
   'dn3': 0.5112269596824073}},
 'cmf': {'mse': {'dt1': 0.29099822844521933,
   'ds1': 0.22602641757240202,
   'ds2': 0.2595752532067127,
   'ds3': 0.2773231888521778,
   'dn1': 0.30301689810864046,
   'dn2': 0.2918296819190488,
   'dn3': 0.29457170511419123},
  'auc': {'dt1': 0.49886283269631354,
   'ds1': 0.48994947287180834,
   'ds2': 0.49030929107923593,
   'ds3': 0.5006059124287411,
   'dn1': 0.4986257842910373,
   'dn2': 0.5018123759691793,
   'dn3': 0.49643930870937736}},
 'gcmf': {'mse': {'dt1': 0.3285807704726244,
   'ds1': 0.264495937268759,
   'ds2': 0.28089295132098785,
   'ds3': 0.3065126678350034,
   'dn1': 0.3709508458553222,
   'dn2': 0.33972791552443776,
   'dn3': 0.35650233333145614},
  'auc': {'dt1': 0.5074029599521301,
   'ds1': 0.49550389529592154,
   'ds2': 0.5004454320833291,
   'ds3': 0.4981464991719114,
   'dn1': 0.4997351913394744,
   'dn2': 0.5040195173369497,
   'dn3': 0.4909185373343909}}}

In [8]:
pd.json_normalize(dict_result)

,ncmf.mse.dt1,ncmf.mse.ds1,ncmf.mse.ds2,ncmf.mse.ds3,ncmf.mse.dn1,ncmf.mse.dn2,ncmf.mse.dn3,ncmf.auc.dt1,ncmf.auc.ds1,ncmf.auc.ds2,...,gcmf.mse.dn1,gcmf.mse.dn2,gcmf.mse.dn3,gcmf.auc.dt1,gcmf.auc.ds1,gcmf.auc.ds2,gcmf.auc.ds3,gcmf.auc.dn1,gcmf.auc.dn2,gcmf.auc.dn3
0,0.163706,0.143782,0.15189,0.160329,0.160999,0.16518,0.160397,0.560072,0.481039,0.585012,...,0.370951,0.339728,0.356502,0.507403,0.495504,0.500445,0.498146,0.499735,0.50402,0.490919

In [9]:
df = pd.DataFrame.from_dict(dict_result,orient="index").stack().to_frame()
df_result = pd.DataFrame(df[0].values.tolist(), index=df.index).T
df_result

         ncmf                dfmf                dcmf                 cmf  \
          mse       auc       mse       auc       mse       auc       mse
dt1  0.163706  0.560072  0.340705  0.499025  0.285424  0.638339  0.290998
ds1  0.143782  0.481039  0.359807  0.500800  0.303814  0.501538  0.226026
ds2  0.151890  0.585012  0.347501  0.487822  0.209601  0.452979  0.259575
ds3  0.160329  0.563579  0.332953  0.489687  0.221195  0.176654  0.277323
dn1  0.160999  0.538091  0.341305  0.503115  0.287399  0.540039  0.303017
dn2  0.165180  0.505592  0.340106  0.509187  0.310910  0.512485  0.291830
dn3  0.160397  0.527629  0.343880  0.495761  0.299696  0.511227  0.294572

                   gcmf
          auc       mse       auc
dt1  0.498863  0.328581  0.507403
ds1  0.489949  0.264496  0.495504
ds2  0.490309  0.280893  0.500445
ds3  0.500606  0.306513  0.498146
dn1  0.498626  0.370951  0.499735
dn2  0.501812  0.339728  0.504020
dn3  0.496439  0.356502  0.490919

In [16]:
list_datasets = ["dfmf","dcmf","cmf","gcmf"]
#
list_diff_mse = []
for cur_dataset in list_datasets:
    list_diff_mse.append(df_result["ncmf"]["mse"] - df_result[cur_dataset]["mse"])
df_diff_mse = pd.concat(list_diff_mse,axis=1)
df_diff_mse.columns = list_datasets
#
list_diff_auc = []
for cur_dataset in list_datasets:
    list_diff_auc.append(df_result["ncmf"]["auc"] - df_result[cur_dataset]["auc"])
df_diff_auc = pd.concat(list_diff_auc,axis=1)
df_diff_auc.columns = list_datasets

In [17]:
df_diff_auc

         dfmf      dcmf       cmf      gcmf
dt1  0.061048 -0.078267  0.061210  0.052669
ds1 -0.019761 -0.020500 -0.008911 -0.014465
ds2  0.097189  0.132032  0.094702  0.084566
ds3  0.073892  0.386925  0.062973  0.065433
dn1  0.034976 -0.001948  0.039465  0.038355
dn2 -0.003595 -0.006892  0.003780  0.001573
dn3  0.031868  0.016402  0.031190  0.036710

In [18]:
df_diff_mse

         dfmf      dcmf       cmf      gcmf
dt1 -0.176999 -0.121718 -0.127293 -0.164875
ds1 -0.216024 -0.160032 -0.082244 -0.120714
ds2 -0.195611 -0.057711 -0.107685 -0.129003
ds3 -0.172625 -0.060866 -0.116995 -0.146184
dn1 -0.180306 -0.126400 -0.142017 -0.209951
dn2 -0.174926 -0.145730 -0.126650 -0.174548
dn3 -0.183483 -0.139299 -0.134175 -0.196105