Here, we compare the reconstructed matrices from NCMF, NIMCGCN, GRGMF and CSGNN over the test split.

In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_id = 3

In [3]:
ncmf_recon_file = f"../../datasets/NCMF/PolyP3/{sample_id}/X1.npy"
ncmf_x1 = np.load(ncmf_recon_file, allow_pickle=True)
print(ncmf_x1.shape)
ncmf_x1

(645, 837)

array([[1.5469407, 1.5469407, 1.5469407, ..., 1.5473185, 1.5469407,
        1.5473185],
       [1.5469407, 1.5469407, 1.5469407, ..., 1.5473185, 1.5473185,
        1.5473185],
       [1.5469407, 1.5469407, 1.5469407, ..., 1.5473185, 1.5473185,
        1.5473185],
       ...,
       [1.5469407, 1.5473185, 1.5469407, ..., 1.5473185, 1.5473185,
        1.5473185],
       [1.5469407, 1.5473185, 1.5469407, ..., 1.5473185, 1.5473185,
        1.5473185],
       [1.5473185, 1.5469407, 1.5469407, ..., 1.5473185, 1.5473185,
        1.5473185]], dtype=float32)

In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /home/ajayago/anaconda3/envs/ncmf/lib/python3.7/site-packages (from openpyxl) (1.1.0)

In [5]:
grgmf_recon_file = f"../../GRGMF/output/PolyP3_{sample_id}_predicted_matrix.xlsx"
grgmf_x1 = pd.read_excel(grgmf_recon_file, engine="openpyxl", index_col=0)
print(grgmf_x1.shape)
grgmf_x1

(645, 837)

,protein_3356,protein_3358,protein_3357,protein_3350,protein_150,protein_151,protein_152,protein_4988,protein_1814,protein_148,...,protein_51069,protein_6476,protein_3948,protein_728378,protein_4126,protein_84816,protein_4190,protein_92483,protein_10988,protein_221656
CID000000085,0.265701,0.166927,0.201678,0.148577,0.140126,0.183291,0.124432,0.168243,0.172818,0.099449,...,0.001850,0.007279,0.002547,0.004079,0.001852,0.002505,0.002910,0.002716,0.002466,0.010555
CID000000119,0.028522,0.008427,0.018577,0.034796,0.009815,0.078158,0.044661,0.012916,0.013108,0.007465,...,0.001773,0.002888,0.001297,0.001575,0.000692,0.001171,0.001385,0.001297,0.001770,0.004563
CID000000143,0.309518,0.163084,0.243853,0.142971,0.107306,0.139758,0.119250,0.205465,0.179952,0.093221,...,0.002923,0.010271,0.003408,0.009831,0.002944,0.002993,0.004001,0.003690,0.004112,0.014028
CID000000158,0.223926,0.149162,0.148767,0.143188,0.092166,0.141430,0.081508,0.165310,0.154832,0.090340,...,0.002036,0.006896,0.002488,0.003535,0.001768,0.002560,0.002837,0.002607,0.002551,0.010219
CID000000159,0.220817,0.150404,0.173309,0.144710,0.107597,0.158119,0.096884,0.157200,0.188207,0.077043,...,0.001257,0.004832,0.001426,0.002598,0.001041,0.001383,0.001658,0.001521,0.001648,0.007361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CID006435110,0.233175,0.180141,0.246236,0.133810,0.115205,0.172419,0.101134,0.161860,0.204350,0.109638,...,0.001412,0.005430,0.001796,0.002645,0.001243,0.001821,0.002060,0.001910,0.001843,0.008366
CID006436173,0.052036,0.052159,0.107755,0.080708,0.043660,0.070037,0.030897,0.093494,0.083263,0.034914,...,0.000693,0.002874,0.000961,0.001254,0.000738,0.001002,0.001102,0.001032,0.000890,0.004279
CID006447131,0.255467,0.210845,0.251969,0.186627,0.155280,0.244308,0.124706,0.199895,0.240977,0.133184,...,0.001277,0.005321,0.001663,0.002375,0.001154,0.001702,0.001918,0.001764,0.001677,0.008651
CID006918453,0.151206,0.117173,0.153990,0.097969,0.075260,0.124917,0.061869,0.131856,0.130791,0.074403,...,0.001219,0.004747,0.001715,0.002173,0.001150,0.001814,0.001949,0.001808,0.001570,0.007247
CID009571074,0.532374,0.197577,0.346810,0.278210,0.248558,0.843375,0.424519,0.359971,0.161059,0.299190,...,0.001269,0.006567,0.002033,0.002706,0.001136,0.002046,0.002311,0.002091,0.001794,0.012900

In [6]:
nimcgcn_drug_repr = np.load(f"../../NIMCGCN/data/PolyP3/{sample_id}/drug_repr.npy", allow_pickle=True)
nimcgcn_protein_repr = np.load(f"../../NIMCGCN/data/PolyP3/{sample_id}/protein_repr.npy", allow_pickle=True)
print(nimcgcn_drug_repr.shape, nimcgcn_protein_repr.shape)

(645, 64) (837, 64)

In [7]:
nimcgcn_x1 = np.matmul(nimcgcn_drug_repr, np.transpose(nimcgcn_protein_repr))
print(nimcgcn_x1.shape)
nimcgcn_x1

(645, 837)

array([[0.05027676, 0.04848009, 0.04859864, ..., 0.01823063, 0.00445523,
        0.00977796],
       [0.0189713 , 0.01829406, 0.01835944, ..., 0.00686055, 0.0021014 ,
        0.00504152],
       [0.        , 0.        , 0.        , ..., 0.02765291, 0.00361483,
        0.00860628],
       ...,
       [0.01339142, 0.01290692, 0.01294356, ..., 0.01652473, 0.00259547,
        0.00469482],
       [0.00067724, 0.00065274, 0.00065459, ..., 0.01450769, 0.00301582,
        0.00510769],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00237136]], dtype=float32)

In [8]:
original_x1 = pd.read_csv(f"../../datasets/NCMF/PolyP3/drug-protein.csv", header=None)
print(original_x1.shape)
original_x1

(645, 837)

,0,1,2,3,4,5,6,7,8,9,...,827,828,829,830,831,832,833,834,835,836
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
641,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
642,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
644,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
test_x1 = pd.read_csv(f"../../datasets/NCMF/PolyP3/sampled{sample_id}_link.dat.test", sep="\t", header=None)
test_x1.columns = ["left", "right", "value"]
test_x1

        left  right  value
0         28   1404      0
1        549    711      0
2        226   1244      0
3        196   1189      0
4        383   1001      0
...      ...    ...    ...
107968   216    851      0
107969   402   1434      0
107970   260    913      0
107971   374   1349      0
107972   616   1448      0

[107973 rows x 3 columns]

In [10]:
def get_value(row, array):
    i = int(row["left"])
    j = int(row["right"]) - 645
    return array[i][j]

In [11]:
test_x1["ncmf_recon"] = test_x1.apply(lambda row: get_value(row, ncmf_x1), axis = 1)
test_x1

        left  right  value  ncmf_recon
0         28   1404      0    1.547318
1        549    711      0    1.547318
2        226   1244      0    1.546941
3        196   1189      0    1.547318
4        383   1001      0    1.546941
...      ...    ...    ...         ...
107968   216    851      0    1.547318
107969   402   1434      0    1.546941
107970   260    913      0    1.547318
107971   374   1349      0    1.547318
107972   616   1448      0    1.546941

[107973 rows x 4 columns]

In [12]:
test_x1["grgmf_recon"] = test_x1.apply(lambda row: get_value(row, grgmf_x1.values), axis = 1)
test_x1

        left  right  value  ncmf_recon  grgmf_recon
0         28   1404      0    1.547318     0.003315
1        549    711      0    1.547318     0.006511
2        226   1244      0    1.546941     0.024126
3        196   1189      0    1.547318     0.000865
4        383   1001      0    1.546941     0.006107
...      ...    ...    ...         ...          ...
107968   216    851      0    1.547318     0.011645
107969   402   1434      0    1.546941     0.002147
107970   260    913      0    1.547318     0.009999
107971   374   1349      0    1.547318     0.002204
107972   616   1448      0    1.546941     0.004858

[107973 rows x 5 columns]

In [13]:
test_x1["nimcgcn_recon"] = test_x1.apply(lambda row: get_value(row, nimcgcn_x1), axis = 1)
test_x1

        left  right  value  ncmf_recon  grgmf_recon  nimcgcn_recon
0         28   1404      0    1.547318     0.003315       0.000000
1        549    711      0    1.547318     0.006511       0.027727
2        226   1244      0    1.546941     0.024126       0.018454
3        196   1189      0    1.547318     0.000865       0.009128
4        383   1001      0    1.546941     0.006107       0.000000
...      ...    ...    ...         ...          ...            ...
107968   216    851      0    1.547318     0.011645       0.030991
107969   402   1434      0    1.546941     0.002147       0.000000
107970   260    913      0    1.547318     0.009999       0.020218
107971   374   1349      0    1.547318     0.002204       0.008515
107972   616   1448      0    1.546941     0.004858       0.000000

[107973 rows x 6 columns]

In [14]:
from sklearn.preprocessing import MinMaxScaler
test_x1["ncmf_recon_min_max_scaled"] = MinMaxScaler().fit_transform(test_x1[["ncmf_recon"]])

In [15]:
test_x1

,left,right,value,ncmf_recon,grgmf_recon,nimcgcn_recon,ncmf_recon_min_max_scaled
0,28,1404,0,1.547318,0.003315,0.000000,1.0
1,549,711,0,1.547318,0.006511,0.027727,1.0
2,226,1244,0,1.546941,0.024126,0.018454,0.0
3,196,1189,0,1.547318,0.000865,0.009128,1.0
4,383,1001,0,1.546941,0.006107,0.000000,0.0
...,...,...,...,...,...,...,...
107968,216,851,0,1.547318,0.011645,0.030991,1.0
107969,402,1434,0,1.546941,0.002147,0.000000,0.0
107970,260,913,0,1.547318,0.009999,0.020218,1.0
107971,374,1349,0,1.547318,0.002204,0.008515,1.0
107972,616,1448,0,1.546941,0.004858,0.000000,0.0

In [16]:
y_true = list(test_x1["value"])

In [17]:
from sklearn.metrics import mean_squared_error
print("NCMF")
print(mean_squared_error(y_true, list(test_x1["ncmf_recon"])))
print("GRGMF")
print(mean_squared_error(y_true, list(test_x1["grgmf_recon"])))
print("NIMCGCN")
print(mean_squared_error(y_true, list(test_x1["nimcgcn_recon"])))

NCMF
2.334577826601074
GRGMF
0.009933405942178236
NIMCGCN
0.008579164540771199

In [18]:
from sklearn.metrics import roc_auc_score, precision_recall_curve, auc
auroc = roc_auc_score(y_true, list(test_x1["ncmf_recon_min_max_scaled"]))
precision, recall, thresholds = precision_recall_curve(y_true, list(test_x1["ncmf_recon_min_max_scaled"]))
auprc = auc(recall, precision)
print("NCMF")
print(f"AUROC = {auroc}")
print(f"AUPRC = {auprc}")

NCMF
AUROC = 0.4577539247996814
AUPRC = 0.3893810059174891

In [19]:
auroc = roc_auc_score(y_true, list(test_x1["ncmf_recon"]))
precision, recall, thresholds = precision_recall_curve(y_true, list(test_x1["ncmf_recon"]))
auprc = auc(recall, precision)
print("NCMF")
print(f"AUROC = {auroc}")
print(f"AUPRC = {auprc}")

NCMF
AUROC = 0.4577539247996814
AUPRC = 0.3893810059174891

In [20]:
auroc = roc_auc_score(y_true, list(test_x1["grgmf_recon"]))
precision, recall, thresholds = precision_recall_curve(y_true, list(test_x1["grgmf_recon"]))
auprc = auc(recall, precision)
print("GRGMF")
print(f"AUROC = {auroc}")
print(f"AUPRC = {auprc}")

GRGMF
AUROC = 0.9897922501425518
AUPRC = 0.8574782404751778

In [21]:
auroc = roc_auc_score(y_true, list(test_x1["nimcgcn_recon"]))
precision, recall, thresholds = precision_recall_curve(y_true, list(test_x1["nimcgcn_recon"]))
auprc = auc(recall, precision)
print("NIMCGCN")
print(f"AUROC = {auroc}")
print(f"AUPRC = {auprc}")

NIMCGCN
AUROC = 0.9499750761912649
AUPRC = 0.8248498480986053